/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as StratifyX from "../../../../api/index";
import * as core from "../../../../core";
import { GenericEvent } from "../../../types/GenericEvent";
export declare const Response: core.serialization.Schema<serializers.studiesMonteCarlo.getMonteCarloEvents.Response.Raw, StratifyX.GenericEvent[]>;
export declare namespace Response {
    type Raw = GenericEvent.Raw[];
}
