# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .meta_data_option import MetaDataOption


class AlgorithmBaseMetaData(UniversalBaseModel):
    """
    Algorithm metadata (see `epoch_script::strategy::AlgorithmBaseMetaData`)
    """

    id: str
    name: typing.Optional[str] = None
    options: typing.Optional[typing.List[MetaDataOption]] = None
    desc: typing.Optional[str] = None
    tags: typing.Optional[typing.List[str]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
