# This file was auto-generated by Fern from our API Definition.

import typing

AssetSpecificationAssetClass = typing.Union[typing.Literal["Stocks", "FX", "Crypto", "Futures", "Indices"], typing.Any]
