# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .asset_specification_data_asset_class import AssetSpecificationDataAssetClass
from .polygon_metadata import PolygonMetadata


class AssetSpecificationData(UniversalBaseModel):
    """
    Asset specification (see `data_sdk::asset::AssetSpecificationData`)
    """

    id: str
    name: typing.Optional[str] = None
    ticker: typing.Optional[str] = None
    asset_class: typing.Optional[AssetSpecificationDataAssetClass] = pydantic.Field(default=None)
    """
    Asset class type
    """

    exchange: typing.Optional[str] = None
    currency: typing.Optional[str] = None
    industry: typing.Optional[str] = None
    sector: typing.Optional[str] = None
    multiplier: typing.Optional[float] = None
    min_tick: typing.Optional[float] = None
    category: typing.Optional[str] = None
    eod_start: typing.Optional[dt.date] = None
    eod_end: typing.Optional[dt.date] = None
    minute_start: typing.Optional[dt.date] = None
    minute_end: typing.Optional[dt.date] = None
    expiry_months: typing.Optional[str] = None
    vendor: typing.Optional[str] = pydantic.Field(default=None)
    """
    MarketDataVendor enum (e.g. Archive, Polygon)
    """

    polygon_metadata: typing.Optional[PolygonMetadata] = None
    last_updated: typing.Optional[dt.date] = None
    data_source: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
