# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class BoxSchema(UniversalBaseModel):
    """
    Box rendering schema for FVG, Order Blocks, Gaps, Liquidity zones
    """

    top_key: str = pydantic.Field(alias="topKey")
    bottom_key: str = pydantic.Field(alias="bottomKey")
    signal_key: typing.Optional[str] = pydantic.Field(alias="signalKey", default=None)
    end_index_key: typing.Optional[str] = pydantic.Field(alias="endIndexKey", default=None)
    bull_color: typing.Optional[typing.Any] = pydantic.Field(alias="bullColor", default=None)
    bear_color: typing.Optional[typing.Any] = pydantic.Field(alias="bearColor", default=None)
    opacity: typing.Optional[float] = None
    show_label: typing.Optional[bool] = pydantic.Field(alias="showLabel", default=None)
    label_text: typing.Optional[str] = pydantic.Field(alias="labelText", default=None)

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
