# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .color import Color


class CandlestickSpec(UniversalBaseModel):
    """
    Candlestick (OHLCV) specification embedded in GenericSchema
    """

    open_key: typing.Optional[str] = pydantic.Field(alias="openKey", default=None)
    high_key: typing.Optional[str] = pydantic.Field(alias="highKey", default=None)
    low_key: typing.Optional[str] = pydantic.Field(alias="lowKey", default=None)
    close_key: typing.Optional[str] = pydantic.Field(alias="closeKey", default=None)
    volume_key: typing.Optional[str] = pydantic.Field(alias="volumeKey", default=None)
    up_color: typing.Optional[Color] = pydantic.Field(alias="upColor", default=None)
    down_color: typing.Optional[Color] = pydantic.Field(alias="downColor", default=None)

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
