# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class CategoryMetaData(UniversalBaseModel):
    """
    Category metadata (see `epoch_folio::CategoryMetaData`)
    """

    value: typing.Optional[str] = None
    label: typing.Optional[str] = None
    description: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
