# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .chart_y_axis import ChartYAxis
from .series_info import SeriesInfo
from .session_range import SessionRange


class ChartPaneMetadata(UniversalBaseModel):
    y_axis: typing.List[ChartYAxis] = pydantic.Field(alias="yAxis")
    series: typing.List[SeriesInfo]
    session_ranges: typing.List[SessionRange] = pydantic.Field(alias="sessionRanges")

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
