# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .column_filter_metadata_type import ColumnFilterMetadataType
from .filter_operator import FilterOperator


class ColumnFilterMetadata(UniversalBaseModel):
    column_name: str
    display_name: str
    type: ColumnFilterMetadataType
    supported_operators: typing.List[FilterOperator]
    options: typing.List[str]
    min_value: typing.Optional[float] = None
    max_value: typing.Optional[float] = None
    min_timestamp: typing.Optional[int] = None
    max_timestamp: typing.Optional[int] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
