# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class DatePeriodConfig(UniversalBaseModel):
    """
    Date period config (see `epoch_script::strategy::DatePeriodConfig`)
    """

    start: dt.date
    end: dt.date

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
