# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class ErrorResponse(UniversalBaseModel):
    """
    Error response (see `epoch_core::ErrorContext`, emitted via `epoch_stratifyx::server::SendError`)
    """

    error: str = pydantic.Field()
    """
    Machine-readable error type
    """

    message: str = pydantic.Field()
    """
    Human-readable error message
    """

    timestamp: str = pydantic.Field()
    """
    ISO-8601 UTC timestamp (no timezone suffix)
    """

    additional_context: typing.Optional[typing.Dict[str, str]] = pydantic.Field(alias="additionalContext", default=None)
    """
    Additional structured context (string map)
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
