# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .templated_generic_function import TemplatedGenericFunction


class ExecutionCostConfig(UniversalBaseModel):
    """
    Hierarchical execution cost configuration (see `epoch_stratifyx::ExecutionCostConfig<T>`)
    """

    model: typing.Optional[TemplatedGenericFunction] = None
    default_model: typing.Optional[TemplatedGenericFunction] = None
    asset_class_overrides: typing.Optional[typing.Dict[str, TemplatedGenericFunction]] = None
    symbol_overrides: typing.Optional[typing.Dict[str, TemplatedGenericFunction]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
