# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .filter_condition import FilterCondition
from .logical_operator import LogicalOperator


class FilterExpression(UniversalBaseModel):
    """
    Complex filter expression (see `api::v1::FilterExpression`)
    """

    conditions: typing.List[FilterCondition]
    logical_operators: typing.List[LogicalOperator] = pydantic.Field()
    """
    Logical operators combining conditions; should be conditions.length - 1
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
