# This file was auto-generated by Fern from our API Definition.

import typing

FilterOperator = typing.Union[
    typing.Literal[
        "Equals",
        "NotEquals",
        "GreaterThan",
        "GreaterThanOrEqual",
        "LessThan",
        "LessThanOrEqual",
        "Contains",
        "NotContains",
        "Between",
        "NotBetween",
        "Null",
    ],
    typing.Any,
]
