# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .table_metadata_column_def import TableMetadataColumnDef


class FullTableMetaData(UniversalBaseModel):
    """
    Full table metadata for a single (timeframe, asset) table (see `api::v1::FullTableMetaData`)
    """

    start_ts: int = pydantic.Field()
    """
    Start timestamp (nanoseconds)
    """

    start_ts_str: str
    end_ts: int = pydantic.Field()
    """
    End timestamp (nanoseconds)
    """

    end_ts_str: str
    total_size: int
    index_type: str
    columns: typing.List[TableMetadataColumnDef]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
