# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .meta_data_option import MetaDataOption


class FuturesContinuationMetaData(UniversalBaseModel):
    """
    Futures continuation rollover metadata
    """

    id: str
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    RolloverType enum
    """

    params: typing.Optional[typing.List[MetaDataOption]] = None
    tags: typing.Optional[typing.List[str]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
