# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class GenericAliasSpec(UniversalBaseModel):
    """
    Generic alias resolution spec (see `epoch_script::transforms::GenericAliasSpec`)
    """

    name: str
    resolution: int = pydantic.Field()
    """
    GenericResolutionType enum: 0=ByFirstInput,1=ByBranchInput,2=ByOutputType
    """

    resolution_input_id: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
