# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .area_range_spec import AreaRangeSpec
from .column_spec import ColumnSpec
from .h_line_spec import HLineSpec
from .line_spec import LineSpec
from .plot_band_spec import PlotBandSpec
from .scatter_spec import ScatterSpec


class GenericSchema(UniversalBaseModel):
    """
    Generic rendering schema for indicators (lines, scatter, columns, etc.)
    """

    lines: typing.Optional[typing.List[LineSpec]] = None
    h_lines: typing.Optional[typing.List[HLineSpec]] = pydantic.Field(alias="hLines", default=None)
    scatter: typing.Optional[typing.List[ScatterSpec]] = None
    columns: typing.Optional[typing.List[ColumnSpec]] = None
    area_ranges: typing.Optional[typing.List[AreaRangeSpec]] = pydantic.Field(alias="areaRanges", default=None)
    plot_bands: typing.Optional[typing.List[PlotBandSpec]] = pydantic.Field(alias="plotBands", default=None)
    separate_panel: typing.Optional[bool] = pydantic.Field(alias="separatePanel", default=None)
    y_min: typing.Optional[float] = pydantic.Field(alias="yMin", default=None)
    y_max: typing.Optional[float] = pydantic.Field(alias="yMax", default=None)

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
