# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .job_list_item_status import JobListItemStatus
from .job_period import JobPeriod


class JobListItem(UniversalBaseModel):
    """
    Job/execution list item (see `epoch_stratifyx::server::JobListItem`)
    """

    id: str
    definition_id: str
    status: JobListItemStatus = pydantic.Field()
    """
    pending, running, completed, failed, cancelled
    """

    period: typing.Optional[JobPeriod] = None
    created_at: int = pydantic.Field()
    """
    Unix timestamp in milliseconds
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
