# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .event_context import EventContext
from .operation_status import OperationStatus


class LifecycleEvent(UniversalBaseModel):
    timestamp: int = pydantic.Field()
    """
    Unix timestamp in milliseconds (system_clock)
    """

    path: str = pydantic.Field()
    """
    Event path (string form)
    """

    context: EventContext
    status: OperationStatus
    operation_type: str
    operation_name: str
    duration: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in milliseconds
    """

    error_message: typing.Optional[str] = None
    items_succeeded: typing.Optional[int] = None
    items_failed: typing.Optional[int] = None
    items_skipped: typing.Optional[int] = None
    items_total: typing.Optional[int] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
