# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class LineSpec(UniversalBaseModel):
    data_key: str = pydantic.Field(alias="dataKey")
    name: str
    color: typing.Optional[typing.Any] = None
    dash_style: typing.Optional[typing.Any] = pydantic.Field(alias="dashStyle", default=None)
    line_width: typing.Optional[int] = pydantic.Field(alias="lineWidth", default=None)
    step: typing.Optional[bool] = None
    enable_markers: typing.Optional[bool] = pydantic.Field(alias="enableMarkers", default=None)

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
