# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .event_context import EventContext
from .log_level import LogLevel


class LogEvent(UniversalBaseModel):
    timestamp: int
    path: str
    context: EventContext
    level: LogLevel
    message: str
    source: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
