# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .meta_data_option_definition import MetaDataOptionDefinition
from .meta_data_option_type import MetaDataOptionType
from .select_option import SelectOption


class MetaDataOption(UniversalBaseModel):
    """
    Metadata option descriptor (see `epoch_script::MetaDataOption`)
    """

    id: str
    name: typing.Optional[str] = None
    type: typing.Optional[MetaDataOptionType] = None
    default_value: typing.Optional[MetaDataOptionDefinition] = pydantic.Field(alias="defaultValue", default=None)
    is_required: typing.Optional[bool] = pydantic.Field(alias="isRequired", default=None)
    select_option: typing.Optional[typing.List[SelectOption]] = pydantic.Field(alias="selectOption", default=None)
    min: typing.Optional[float] = None
    max: typing.Optional[float] = None
    step_size: typing.Optional[float] = None
    desc: typing.Optional[str] = None
    tuning_guidance: typing.Optional[str] = pydantic.Field(alias="tuningGuidance", default=None)

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
