# This file was auto-generated by Fern from our API Definition.

import typing

from .event_marker_schema import EventMarkerSchema
from .meta_data_arg_ref import MetaDataArgRef
from .sequence import Sequence
from .session_anchor_value import SessionAnchorValue
from .session_type_value import SessionTypeValue
from .table_report_schema import TableReportSchema
from .time_delta import TimeDelta
from .time_of_day import TimeOfDay

MetaDataOptionDefinition = typing.Union[
    float,
    bool,
    str,
    MetaDataArgRef,
    TimeOfDay,
    TimeDelta,
    SessionTypeValue,
    SessionAnchorValue,
    EventMarkerSchema,
    TableReportSchema,
    Sequence,
]
