# This file was auto-generated by Fern from our API Definition.

import typing

from .algorithm_base_meta_data import AlgorithmBaseMetaData
from .asset_specification_data import AssetSpecificationData
from .category_meta_data import CategoryMetaData
from .execution_cost_meta_data import ExecutionCostMetaData
from .futures_continuation_meta_data import FuturesContinuationMetaData
from .index_constituents_data import IndexConstituentsData
from .table_column_metadata import TableColumnMetadata
from .time_frame_selector import TimeFrameSelector
from .transform_category_meta_data import TransformCategoryMetaData
from .transforms_meta_data import TransformsMetaData

MetadataResponse = typing.Union[
    typing.List[TransformsMetaData],
    typing.List[AlgorithmBaseMetaData],
    typing.List[CategoryMetaData],
    typing.List[TableColumnMetadata],
    typing.List[TimeFrameSelector],
    typing.List[TransformCategoryMetaData],
    typing.List[AssetSpecificationData],
    IndexConstituentsData,
    typing.List[ExecutionCostMetaData],
    typing.List[FuturesContinuationMetaData],
]
