# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class MetricsResponse(UniversalBaseModel):
    """
    Computed metrics (keys are metric names; values are numeric)
    """

    sharpe: typing.Optional[float] = None
    sortino: typing.Optional[float] = None
    calmar: typing.Optional[float] = None
    max_drawdown: typing.Optional[float] = None
    annual_return: typing.Optional[float] = None
    annual_volatility: typing.Optional[float] = None
    cum_return: typing.Optional[float] = None
    omega: typing.Optional[float] = None
    var: typing.Optional[float] = None
    cvar: typing.Optional[float] = None
    skew: typing.Optional[float] = None
    kurtosis: typing.Optional[float] = None
    tail_ratio: typing.Optional[float] = None
    stability_of_time_series: typing.Optional[float] = None
    common_sense_ratio: typing.Optional[float] = None
    alpha: typing.Optional[float] = None
    beta: typing.Optional[float] = None
    profit_factor: typing.Optional[float] = None
    win_rate: typing.Optional[float] = None
    avg_win_loss_ratio: typing.Optional[float] = None
    total_trades: typing.Optional[float] = None
    avg_trade_pnl: typing.Optional[float] = None
    gross_profit: typing.Optional[float] = None
    gross_loss: typing.Optional[float] = None
    largest_win: typing.Optional[float] = None
    largest_loss: typing.Optional[float] = None
    winning_trades: typing.Optional[float] = None
    losing_trades: typing.Optional[float] = None
    avg_duration: typing.Optional[float] = None
    median_duration: typing.Optional[float] = None
    avg_trade_return: typing.Optional[float] = None
    median_trade_return: typing.Optional[float] = None
    kelly_fraction: typing.Optional[float] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
