# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class NullPolicy(UniversalBaseModel):
    """
    Null handling policy (see `epoch_core::NullPolicy`)
    """

    input: str
    output: str
    constant_value: typing.Optional[float] = pydantic.Field(alias="constantValue", default=None)

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
