# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .scalar_json import ScalarJson


class OrderRow(UniversalBaseModel):
    """
    Order row (JSON-encoded Arrow table row; columns match `GetOrderTableHeader()` + index)
    """

    index: typing.Optional[ScalarJson] = None
    asset: typing.Optional[str] = None
    updated_at: typing.Optional[dt.datetime] = None
    status: typing.Optional[str] = None
    side: typing.Optional[str] = None
    type: typing.Optional[str] = None
    quantity: typing.Optional[float] = None
    filled_qty: typing.Optional[float] = None
    filled_price: typing.Optional[float] = None
    is_active: typing.Optional[bool] = None
    limit_price: typing.Optional[float] = None
    stop_price: typing.Optional[float] = None
    id: typing.Optional[str] = None
    oca_group: typing.Optional[str] = None
    parent_id: typing.Optional[str] = None
    failure_reason: typing.Optional[str] = None
    commission: typing.Optional[float] = None
    slippage: typing.Optional[float] = None
    tif: typing.Optional[str] = None
    trail_amount: typing.Optional[float] = None
    hwm: typing.Optional[float] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
