# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .generic_event import GenericEvent
from .pagination_info import PaginationInfo


class PaginatedEventsResponse(UniversalBaseModel):
    """
    Paginated events response
    """

    events: typing.List[GenericEvent]
    pagination: PaginationInfo

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
