# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .arrow_table_rows import ArrowTableRows


class PaginatedTableResponse(UniversalBaseModel):
    """
    Paginated response for tabular data
    """

    items: ArrowTableRows
    page: int = pydantic.Field()
    """
    Current page number (0-indexed)
    """

    total_pages: int = pydantic.Field()
    """
    Total number of pages
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
