# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .color import Color


class PlotBandSpec(UniversalBaseModel):
    from_: float = pydantic.Field(alias="from")
    to: float
    label: typing.Optional[str] = None
    color: typing.Optional[Color] = None
    opacity: typing.Optional[float] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
