# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class PolygonMetadata(UniversalBaseModel):
    original_ticker: typing.Optional[str] = None
    type: typing.Optional[str] = None
    locale: typing.Optional[str] = None
    cik: typing.Optional[str] = None
    composite_figi: typing.Optional[str] = None
    last_updated: typing.Optional[dt.date] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
