# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .scalar_json import ScalarJson


class PositionRow(UniversalBaseModel):
    """
    Position row (JSON-encoded Arrow table row; columns match `GetPositionTableHeader()` + index)
    """

    index: typing.Optional[ScalarJson] = None
    asset: typing.Optional[str] = None
    quantity: typing.Optional[float] = None
    market_value: typing.Optional[float] = None
    current_price: typing.Optional[float] = None
    updated_at: typing.Optional[dt.datetime] = None
    type: typing.Optional[str] = None
    fx_rate: typing.Optional[float] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
