# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .color import Color
from .marker_symbol import MarkerSymbol


class ScatterSpec(UniversalBaseModel):
    data_key: str = pydantic.Field(alias="dataKey")
    name: str
    color: typing.Optional[Color] = None
    symbol: typing.Optional[MarkerSymbol] = None
    radius: typing.Optional[int] = None
    price_scale_id: typing.Optional[str] = pydantic.Field(alias="priceScaleId", default=None)
    """
    Custom price scale (e.g., 'volume' for volume overlays)
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
