# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class ScatterSpec(UniversalBaseModel):
    data_key: str = pydantic.Field(alias="dataKey")
    name: str
    color: typing.Optional[typing.Any] = None
    symbol: typing.Optional[typing.Any] = None
    radius: typing.Optional[int] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
