# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class SessionSchema(UniversalBaseModel):
    """
    Session rendering schema for trading sessions
    """

    active_key: str = pydantic.Field(alias="activeKey")
    high_key: str = pydantic.Field(alias="highKey")
    low_key: str = pydantic.Field(alias="lowKey")
    color: typing.Optional[typing.Any] = None
    opacity: typing.Optional[float] = None
    border_style: typing.Optional[typing.Any] = pydantic.Field(alias="borderStyle", default=None)

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
