# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .time_of_day import TimeOfDay


class SessionRange(UniversalBaseModel):
    """
    Intraday session range (see `epoch_frame::SessionRange`)
    """

    start: TimeOfDay
    end: TimeOfDay

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
