# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class StudyListItem(UniversalBaseModel):
    """
    Study list item (see `epoch_stratifyx::server::StudyListItem`)
    """

    id: str
    name: str
    description: str
    assets: typing.List[str]
    created_at: int = pydantic.Field()
    """
    Unix timestamp in milliseconds
    """

    updated_at: int = pydantic.Field()
    """
    Unix timestamp in milliseconds
    """

    job_count: int

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
