# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .data_option import DataOption
from .strategy_config_meta_data import StrategyConfigMetaData


class StudyDefinition(UniversalBaseModel):
    """
    StudyDefinition JSON (see `epoch_stratifyx::StudyDefinition`)
    """

    name: str
    description: str
    data: DataOption
    source: str = pydantic.Field()
    """
    EpochScript source code
    """

    metadata: typing.Optional[StrategyConfigMetaData] = None
    global_timeframe: typing.Optional[str] = pydantic.Field(default=None)
    """
    Global timeframe for compilation (default: 1D)
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
