# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .column_filter_metadata import ColumnFilterMetadata


class TableFilterMetadata(UniversalBaseModel):
    columns: typing.List[ColumnFilterMetadata]
    total_rows: int

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
