# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .selectors_metadata import SelectorsMetadata
from .tear_sheet_component_counts import TearSheetComponentCounts


class TearSheetMetadataResponse(UniversalBaseModel):
    """
    Tearsheet metadata response (see StrategyPerfService::GetMetadata)
    """

    tearsheet_metadata: typing.Dict[str, TearSheetComponentCounts]
    selector_metadata: typing.Optional[SelectorsMetadata] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
