# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .meta_data_arg_definition_mapping import MetaDataArgDefinitionMapping


class TemplatedGenericFunction(UniversalBaseModel):
    """
    Templated generic function configuration (see `epoch_script::strategy::TemplatedGenericFunction<T>`)
    """

    type: str = pydantic.Field()
    """
    Algorithm/model type identifier
    """

    args: MetaDataArgDefinitionMapping

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
