# This file was auto-generated by Fern from our API Definition.

import typing

from .custom_fields_option import CustomFieldsOption
from .time_frame_item import TimeFrameItem

TimeFrameSelectorItems = typing.Union[typing.List[TimeFrameItem], CustomFieldsOption]
