# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class TimeOfDay(UniversalBaseModel):
    hour: typing.Optional[int] = None
    minute: typing.Optional[int] = None
    second: typing.Optional[int] = None
    microsecond: typing.Optional[int] = None
    tz: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
