# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class TimeframeInfo(UniversalBaseModel):
    timeframe: str
    absolute_start_ms: int
    absolute_end_ms: int
    total_bars: int

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
