# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .data_info_per_asset import DataInfoPerAsset
from .time_frame_chart_metadata import TimeFrameChartMetadata


class TradeAnalyticsChartMetaData(UniversalBaseModel):
    """
    Trade analytics chart metadata (see `epoch_stratifyx::TradeAnalyticsChartMetaData`)
    """

    asset_info: typing.Dict[str, DataInfoPerAsset]
    chart_info: TimeFrameChartMetadata

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
