# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class TransformCategoryMetaData(UniversalBaseModel):
    """
    Transform category metadata (see `epoch_script::transforms::TransformCategoryMetaData`)
    """

    category: typing.Optional[str] = None
    name: str
    desc: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
