# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class TrendlineSchema(UniversalBaseModel):
    """
    Trendline rendering schema for BOS/CHOCH, chart patterns
    """

    signal_key: typing.Optional[str] = pydantic.Field(alias="signalKey", default=None)
    level_key: str = pydantic.Field(alias="levelKey")
    end_index_key: str = pydantic.Field(alias="endIndexKey")
    bull_color: typing.Optional[typing.Any] = pydantic.Field(alias="bullColor", default=None)
    bear_color: typing.Optional[typing.Any] = pydantic.Field(alias="bearColor", default=None)
    dash_style: typing.Optional[typing.Any] = pydantic.Field(alias="dashStyle", default=None)
    line_width: typing.Optional[int] = pydantic.Field(alias="lineWidth", default=None)
    show_label: typing.Optional[bool] = pydantic.Field(alias="showLabel", default=None)

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
