/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors/index";
import * as StratifyX from "../index";
import * as core from "../../core";
export declare class ForbiddenError extends errors.StratifyXError {
    constructor(body: StratifyX.ErrorResponse, rawResponse?: core.RawResponse);
}
