/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface GetApiV1StudiesExecutionsExecutionIdAnalyticsRequest {
    timeframe?: string;
    assetId?: string;
    fromMs?: number;
    toMs?: number;
    /**
     * Maximum number of items to return
     */
    limit?: number;
}
