/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as StratifyX from "../../../index";
export declare namespace Studies {
    interface Options {
        environment?: core.Supplier<environments.StratifyXEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        fetcher?: core.FetchFunction;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Studies {
    protected readonly _options: Studies.Options;
    constructor(_options?: Studies.Options);
    /**
     * @param {StratifyX.GetApiV1StudiesRequest} request
     * @param {Studies.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     *
     * @example
     *     await client.studies.listStudiesWithJobCounts()
     */
    listStudiesWithJobCounts(request?: StratifyX.GetApiV1StudiesRequest, requestOptions?: Studies.RequestOptions): core.HttpResponsePromise<StratifyX.StudyListItem[]>;
    private __listStudiesWithJobCounts;
    protected _getAuthorizationHeader(): Promise<string | undefined>;
}
