/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as StratifyX from "../../../../../api/index";
import * as core from "../../../../../core";
import { DatePeriodConfig } from "../../../../types/DatePeriodConfig";
import { ExecutionOptions } from "../../../../types/ExecutionOptions";
export declare const ExecuteRequest: core.serialization.Schema<serializers.ExecuteRequest.Raw, StratifyX.ExecuteRequest>;
export declare namespace ExecuteRequest {
    interface Raw {
        id: string;
        period: DatePeriodConfig.Raw;
        execution?: (ExecutionOptions.Raw | null) | null;
    }
}
