/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         source: "source"
 *     }
 */
export interface ValidateSourceRequest {
    /** EpochScript source code to validate */
    source: string;
}
