"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.MonteCarloOption = void 0;
const core = __importStar(require("../../../../../core"));
exports.MonteCarloOption = core.serialization.object({
    nBootstrap: core.serialization.property("n_bootstrap", core.serialization.number().optional()),
    confidenceLevel: core.serialization.property("confidence_level", core.serialization.number().optional()),
    enableBayesian: core.serialization.property("enable_bayesian", core.serialization.boolean().optional()),
    mcmcSamples: core.serialization.property("mcmc_samples", core.serialization.number().optional()),
    mcmcBurnin: core.serialization.property("mcmc_burnin", core.serialization.number().optional()),
    analyzeSharpe: core.serialization.property("analyze_sharpe", core.serialization.boolean().optional()),
    analyzeSortino: core.serialization.property("analyze_sortino", core.serialization.boolean().optional()),
    analyzeMaxDrawdown: core.serialization.property("analyze_max_drawdown", core.serialization.boolean().optional()),
    analyzeReturns: core.serialization.property("analyze_returns", core.serialization.boolean().optional()),
    generateCone: core.serialization.property("generate_cone", core.serialization.boolean().optional()),
    coneDaysForward: core.serialization.property("cone_days_forward", core.serialization.number().optional()),
    conePercentiles: core.serialization.property("cone_percentiles", core.serialization.list(core.serialization.number()).optional()),
});
