/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as StratifyX from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const MonteCarloOption: core.serialization.Schema<serializers.MonteCarloOption.Raw, StratifyX.MonteCarloOption>;
export declare namespace MonteCarloOption {
    interface Raw {
        n_bootstrap?: number | null;
        confidence_level?: number | null;
        enable_bayesian?: boolean | null;
        mcmc_samples?: number | null;
        mcmc_burnin?: number | null;
        analyze_sharpe?: boolean | null;
        analyze_sortino?: boolean | null;
        analyze_max_drawdown?: boolean | null;
        analyze_returns?: boolean | null;
        generate_cone?: boolean | null;
        cone_days_forward?: number | null;
        cone_percentiles?: number[] | null;
    }
}
