# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.data_option import DataOption
from ..types.id_response import IdResponse
from ..types.job_list_item import JobListItem
from ..types.message_response import MessageResponse
from ..types.strategy_config_meta_data import StrategyConfigMetaData
from ..types.study_definition import StudyDefinition
from .raw_client import AsyncRawStudiesDefinitionsClient, RawStudiesDefinitionsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class StudiesDefinitionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawStudiesDefinitionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawStudiesDefinitionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStudiesDefinitionsClient
        """
        return self._raw_client

    def list_study_definitions(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[str]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[str]
            JSON list of definition IDs

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.studies_definitions.list_study_definitions()
        """
        _response = self._raw_client.list_study_definitions(request_options=request_options)
        return _response.data

    def create_study_definition(
        self,
        *,
        name: str,
        description: str,
        data: DataOption,
        source: str,
        metadata: typing.Optional[StrategyConfigMetaData] = OMIT,
        global_timeframe: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IdResponse:
        """
        Parameters
        ----------
        name : str

        description : str

        data : DataOption

        source : str
            EpochScript source code

        metadata : typing.Optional[StrategyConfigMetaData]

        global_timeframe : typing.Optional[str]
            Global timeframe for compilation (default: 1D)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IdResponse
            Created

        Examples
        --------
        from stratifyx import DataOption, StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.studies_definitions.create_study_definition(
            name="name",
            description="description",
            data=DataOption(
                assets=["assets"],
                source="source",
            ),
            source="source",
        )
        """
        _response = self._raw_client.create_study_definition(
            name=name,
            description=description,
            data=data,
            source=source,
            metadata=metadata,
            global_timeframe=global_timeframe,
            request_options=request_options,
        )
        return _response.data

    def get_a_study_definition_by_id(
        self, definition_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> StudyDefinition:
        """
        Parameters
        ----------
        definition_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StudyDefinition
            Study definition

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.studies_definitions.get_a_study_definition_by_id(
            definition_id="definitionId",
        )
        """
        _response = self._raw_client.get_a_study_definition_by_id(definition_id, request_options=request_options)
        return _response.data

    def update_a_study_definition_by_id(
        self,
        definition_id: str,
        *,
        name: str,
        description: str,
        data: DataOption,
        source: str,
        metadata: typing.Optional[StrategyConfigMetaData] = OMIT,
        global_timeframe: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StudyDefinition:
        """
        Parameters
        ----------
        definition_id : str

        name : str

        description : str

        data : DataOption

        source : str
            EpochScript source code

        metadata : typing.Optional[StrategyConfigMetaData]

        global_timeframe : typing.Optional[str]
            Global timeframe for compilation (default: 1D)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StudyDefinition
            Updated definition

        Examples
        --------
        from stratifyx import DataOption, StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.studies_definitions.update_a_study_definition_by_id(
            definition_id="definitionId",
            name="name",
            description="description",
            data=DataOption(
                assets=["assets"],
                source="source",
            ),
            source="source",
        )
        """
        _response = self._raw_client.update_a_study_definition_by_id(
            definition_id,
            name=name,
            description=description,
            data=data,
            source=source,
            metadata=metadata,
            global_timeframe=global_timeframe,
            request_options=request_options,
        )
        return _response.data

    def delete_a_study_definition_and_all_linked_executions(
        self, definition_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageResponse:
        """
        Permanently deletes a study definition and performs a cascading delete of all associated executions (jobs). This operation cannot be undone. All execution results, logs, and analytics data for this study will be permanently removed.

        Parameters
        ----------
        definition_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Study definition and all linked executions deleted successfully

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.studies_definitions.delete_a_study_definition_and_all_linked_executions(
            definition_id="definitionId",
        )
        """
        _response = self._raw_client.delete_a_study_definition_and_all_linked_executions(
            definition_id, request_options=request_options
        )
        return _response.data

    def bulk_delete_study_definitions_and_all_linked_executions(
        self, *, request: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> MessageResponse:
        """
        Permanently deletes multiple study definitions and performs cascading delete of all associated executions (jobs) for each definition. This operation cannot be undone. All execution results, logs, and analytics data for these studies will be permanently removed. Nonexistent IDs are treated as successful (idempotent).

        Parameters
        ----------
        request : typing.Sequence[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Definitions and all linked executions deleted successfully

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.studies_definitions.bulk_delete_study_definitions_and_all_linked_executions(
            request=["string"],
        )
        """
        _response = self._raw_client.bulk_delete_study_definitions_and_all_linked_executions(
            request=request, request_options=request_options
        )
        return _response.data

    def list_jobs_for_a_study_definition(
        self, definition_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[JobListItem]:
        """
        Parameters
        ----------
        definition_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[JobListItem]
            JSON list of jobs for the definition

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.studies_definitions.list_jobs_for_a_study_definition(
            definition_id="definitionId",
        )
        """
        _response = self._raw_client.list_jobs_for_a_study_definition(definition_id, request_options=request_options)
        return _response.data


class AsyncStudiesDefinitionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawStudiesDefinitionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawStudiesDefinitionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStudiesDefinitionsClient
        """
        return self._raw_client

    async def list_study_definitions(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[str]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[str]
            JSON list of definition IDs

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.studies_definitions.list_study_definitions()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_study_definitions(request_options=request_options)
        return _response.data

    async def create_study_definition(
        self,
        *,
        name: str,
        description: str,
        data: DataOption,
        source: str,
        metadata: typing.Optional[StrategyConfigMetaData] = OMIT,
        global_timeframe: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IdResponse:
        """
        Parameters
        ----------
        name : str

        description : str

        data : DataOption

        source : str
            EpochScript source code

        metadata : typing.Optional[StrategyConfigMetaData]

        global_timeframe : typing.Optional[str]
            Global timeframe for compilation (default: 1D)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IdResponse
            Created

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX, DataOption

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.studies_definitions.create_study_definition(
                name="name",
                description="description",
                data=DataOption(
                    assets=["assets"],
                    source="source",
                ),
                source="source",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_study_definition(
            name=name,
            description=description,
            data=data,
            source=source,
            metadata=metadata,
            global_timeframe=global_timeframe,
            request_options=request_options,
        )
        return _response.data

    async def get_a_study_definition_by_id(
        self, definition_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> StudyDefinition:
        """
        Parameters
        ----------
        definition_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StudyDefinition
            Study definition

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.studies_definitions.get_a_study_definition_by_id(
                definition_id="definitionId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_a_study_definition_by_id(definition_id, request_options=request_options)
        return _response.data

    async def update_a_study_definition_by_id(
        self,
        definition_id: str,
        *,
        name: str,
        description: str,
        data: DataOption,
        source: str,
        metadata: typing.Optional[StrategyConfigMetaData] = OMIT,
        global_timeframe: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StudyDefinition:
        """
        Parameters
        ----------
        definition_id : str

        name : str

        description : str

        data : DataOption

        source : str
            EpochScript source code

        metadata : typing.Optional[StrategyConfigMetaData]

        global_timeframe : typing.Optional[str]
            Global timeframe for compilation (default: 1D)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StudyDefinition
            Updated definition

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX, DataOption

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.studies_definitions.update_a_study_definition_by_id(
                definition_id="definitionId",
                name="name",
                description="description",
                data=DataOption(
                    assets=["assets"],
                    source="source",
                ),
                source="source",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_a_study_definition_by_id(
            definition_id,
            name=name,
            description=description,
            data=data,
            source=source,
            metadata=metadata,
            global_timeframe=global_timeframe,
            request_options=request_options,
        )
        return _response.data

    async def delete_a_study_definition_and_all_linked_executions(
        self, definition_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageResponse:
        """
        Permanently deletes a study definition and performs a cascading delete of all associated executions (jobs). This operation cannot be undone. All execution results, logs, and analytics data for this study will be permanently removed.

        Parameters
        ----------
        definition_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Study definition and all linked executions deleted successfully

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.studies_definitions.delete_a_study_definition_and_all_linked_executions(
                definition_id="definitionId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_a_study_definition_and_all_linked_executions(
            definition_id, request_options=request_options
        )
        return _response.data

    async def bulk_delete_study_definitions_and_all_linked_executions(
        self, *, request: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> MessageResponse:
        """
        Permanently deletes multiple study definitions and performs cascading delete of all associated executions (jobs) for each definition. This operation cannot be undone. All execution results, logs, and analytics data for these studies will be permanently removed. Nonexistent IDs are treated as successful (idempotent).

        Parameters
        ----------
        request : typing.Sequence[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Definitions and all linked executions deleted successfully

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.studies_definitions.bulk_delete_study_definitions_and_all_linked_executions(
                request=["string"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.bulk_delete_study_definitions_and_all_linked_executions(
            request=request, request_options=request_options
        )
        return _response.data

    async def list_jobs_for_a_study_definition(
        self, definition_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[JobListItem]:
        """
        Parameters
        ----------
        definition_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[JobListItem]
            JSON list of jobs for the definition

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.studies_definitions.list_jobs_for_a_study_definition(
                definition_id="definitionId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_jobs_for_a_study_definition(
            definition_id, request_options=request_options
        )
        return _response.data
