/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as StratifyX from "../../../index";
import * as stream from "stream";
export declare namespace StudiesAccount {
    interface Options {
        environment?: core.Supplier<environments.StratifyXEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        fetcher?: core.FetchFunction;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class StudiesAccount {
    protected readonly _options: StudiesAccount.Options;
    constructor(_options?: StudiesAccount.Options);
    /**
     * @throws {@link StratifyX.BadRequestError}
     */
    getAccountEquityCurveFile(executionId: string, request?: StratifyX.GetApiV1StudiesExecutionsExecutionIdAccountRequest, requestOptions?: StudiesAccount.RequestOptions): core.HttpResponsePromise<stream.Readable>;
    private __getAccountEquityCurveFile;
    protected _getAuthorizationHeader(): Promise<string | undefined>;
}
