/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as StratifyX from "../../../../api/index";
import * as core from "../../../../core";
import { JobListItem } from "../../../types/JobListItem";
export declare const Response: core.serialization.Schema<serializers.studiesDefinitions.listJobsForAStudyDefinition.Response.Raw, StratifyX.JobListItem[]>;
export declare namespace Response {
    type Raw = JobListItem.Raw[];
}
