# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..types.error_response import ErrorResponse
from ..types.filter_condition import FilterCondition
from ..types.logical_operator import LogicalOperator
from ..types.order_rows import OrderRows
from ..types.table_filter_metadata import TableFilterMetadata
from .types.get_api_v1studies_executions_execution_id_orders_request_sort_direction import (
    GetApiV1StudiesExecutionsExecutionIdOrdersRequestSortDirection,
)
from .types.post_api_v1studies_executions_execution_id_orders_filtered_request_sort_direction import (
    PostApiV1StudiesExecutionsExecutionIdOrdersFilteredRequestSortDirection,
)

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawStudiesOrdersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_order_filter_metadata(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[TableFilterMetadata]:
        """
        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TableFilterMetadata]
            Filter metadata JSON
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/orders/filter-metadata",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TableFilterMetadata,
                    parse_obj_as(
                        type_=TableFilterMetadata,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_orders_tabular_json(
        self,
        execution_id: str,
        *,
        page: typing.Optional[int] = None,
        sort_key: typing.Optional[str] = None,
        sort_direction: typing.Optional[GetApiV1StudiesExecutionsExecutionIdOrdersRequestSortDirection] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[OrderRows]:
        """
        Parameters
        ----------
        execution_id : str

        page : typing.Optional[int]

        sort_key : typing.Optional[str]

        sort_direction : typing.Optional[GetApiV1StudiesExecutionsExecutionIdOrdersRequestSortDirection]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OrderRows]
            Orders JSON array (server-defined shape)
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/orders",
            method="GET",
            params={
                "page": page,
                "sort_key": sort_key,
                "sort_direction": sort_direction,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrderRows,
                    parse_obj_as(
                        type_=OrderRows,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_orders_with_filter_expression(
        self,
        execution_id: str,
        *,
        conditions: typing.Sequence[FilterCondition],
        logical_operators: typing.Sequence[LogicalOperator],
        page: typing.Optional[int] = None,
        sort_key: typing.Optional[str] = None,
        sort_direction: typing.Optional[PostApiV1StudiesExecutionsExecutionIdOrdersFilteredRequestSortDirection] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[OrderRows]:
        """
        Parameters
        ----------
        execution_id : str

        conditions : typing.Sequence[FilterCondition]

        logical_operators : typing.Sequence[LogicalOperator]
            Logical operators combining conditions; should be conditions.length - 1

        page : typing.Optional[int]

        sort_key : typing.Optional[str]

        sort_direction : typing.Optional[PostApiV1StudiesExecutionsExecutionIdOrdersFilteredRequestSortDirection]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OrderRows]
            Orders JSON array (server-defined shape)
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/orders/filtered",
            method="POST",
            params={
                "page": page,
                "sort_key": sort_key,
                "sort_direction": sort_direction,
            },
            json={
                "conditions": conditions,
                "logical_operators": logical_operators,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrderRows,
                    parse_obj_as(
                        type_=OrderRows,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawStudiesOrdersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_order_filter_metadata(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[TableFilterMetadata]:
        """
        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TableFilterMetadata]
            Filter metadata JSON
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/orders/filter-metadata",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TableFilterMetadata,
                    parse_obj_as(
                        type_=TableFilterMetadata,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_orders_tabular_json(
        self,
        execution_id: str,
        *,
        page: typing.Optional[int] = None,
        sort_key: typing.Optional[str] = None,
        sort_direction: typing.Optional[GetApiV1StudiesExecutionsExecutionIdOrdersRequestSortDirection] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[OrderRows]:
        """
        Parameters
        ----------
        execution_id : str

        page : typing.Optional[int]

        sort_key : typing.Optional[str]

        sort_direction : typing.Optional[GetApiV1StudiesExecutionsExecutionIdOrdersRequestSortDirection]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OrderRows]
            Orders JSON array (server-defined shape)
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/orders",
            method="GET",
            params={
                "page": page,
                "sort_key": sort_key,
                "sort_direction": sort_direction,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrderRows,
                    parse_obj_as(
                        type_=OrderRows,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_orders_with_filter_expression(
        self,
        execution_id: str,
        *,
        conditions: typing.Sequence[FilterCondition],
        logical_operators: typing.Sequence[LogicalOperator],
        page: typing.Optional[int] = None,
        sort_key: typing.Optional[str] = None,
        sort_direction: typing.Optional[PostApiV1StudiesExecutionsExecutionIdOrdersFilteredRequestSortDirection] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[OrderRows]:
        """
        Parameters
        ----------
        execution_id : str

        conditions : typing.Sequence[FilterCondition]

        logical_operators : typing.Sequence[LogicalOperator]
            Logical operators combining conditions; should be conditions.length - 1

        page : typing.Optional[int]

        sort_key : typing.Optional[str]

        sort_direction : typing.Optional[PostApiV1StudiesExecutionsExecutionIdOrdersFilteredRequestSortDirection]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OrderRows]
            Orders JSON array (server-defined shape)
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/orders/filtered",
            method="POST",
            params={
                "page": page,
                "sort_key": sort_key,
                "sort_direction": sort_direction,
            },
            json={
                "conditions": conditions,
                "logical_operators": logical_operators,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrderRows,
                    parse_obj_as(
                        type_=OrderRows,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
