/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../../../../index";
/**
 * @example
 *     {
 *         body: {
 *             name: "name",
 *             description: "description",
 *             data: {
 *                 assets: ["assets"],
 *                 source: "source"
 *             },
 *             source: "source"
 *         }
 *     }
 */
export interface PutApiV1StudiesDefinitionsDefinitionIdRequest {
    body: StratifyX.StudyDefinition;
}
