"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetApiV1StudiesExecutionsExecutionIdPositionsRequestSortDirection = void 0;
exports.GetApiV1StudiesExecutionsExecutionIdPositionsRequestSortDirection = {
    Asc: "asc",
    Desc: "desc",
};
