/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type PostApiV1StudiesExecutionsExecutionIdPositionsFilteredRequestSortDirection = "asc" | "desc";
export declare const PostApiV1StudiesExecutionsExecutionIdPositionsFilteredRequestSortDirection: {
    readonly Asc: "asc";
    readonly Desc: "desc";
};
