/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { Color } from "./Color";
export declare const AreaRangeSpec: core.serialization.ObjectSchema<serializers.AreaRangeSpec.Raw, StratifyX.AreaRangeSpec>;
export declare namespace AreaRangeSpec {
    interface Raw {
        upperKey: string;
        lowerKey: string;
        name?: (string | null) | null;
        color?: Color.Raw | null;
        opacity?: (number | null) | null;
    }
}
