/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { ArrowTableRow } from "./ArrowTableRow";
export declare const ArrowTableRows: core.serialization.Schema<serializers.ArrowTableRows.Raw, StratifyX.ArrowTableRows>;
export declare namespace ArrowTableRows {
    type Raw = ArrowTableRow.Raw[];
}
