/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const BoxSchema: core.serialization.ObjectSchema<serializers.BoxSchema.Raw, StratifyX.BoxSchema>;
export declare namespace BoxSchema {
    interface Raw {
        topKey: string;
        bottomKey: string;
        signalKey?: string | null;
        endIndexKey?: string | null;
        bullColor?: unknown | null;
        bearColor?: unknown | null;
        opacity?: number | null;
        showLabel?: boolean | null;
        labelText?: string | null;
    }
}
