/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { Color } from "./Color";
export declare const CandlestickSpec: core.serialization.ObjectSchema<serializers.CandlestickSpec.Raw, StratifyX.CandlestickSpec>;
export declare namespace CandlestickSpec {
    interface Raw {
        openKey?: string | null;
        highKey?: string | null;
        lowKey?: string | null;
        closeKey?: string | null;
        volumeKey?: (string | null) | null;
        upColor?: Color.Raw | null;
        downColor?: Color.Raw | null;
    }
}
