/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const CandlestickSchema: core.serialization.ObjectSchema<serializers.CandlestickSchema.Raw, StratifyX.CandlestickSchema>;
export declare namespace CandlestickSchema {
    interface Raw {
        showRoundTrips: boolean;
        upColor?: unknown | null;
        downColor?: unknown | null;
    }
}
