/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { ScalarJson } from "./ScalarJson";
export declare const CardColumnSchema: core.serialization.ObjectSchema<serializers.CardColumnSchema.Raw, StratifyX.CardColumnSchema>;
export declare namespace CardColumnSchema {
    interface Raw {
        column_id: string;
        slot: string;
        render_type: string;
        color_map: Record<string, (ScalarJson.Raw | null)[]>;
        label?: (string | null) | null;
    }
}
