/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { ChartYAxis } from "./ChartYAxis";
import { SeriesInfo } from "./SeriesInfo";
import { SessionRange } from "./SessionRange";
export declare const ChartPaneMetadata: core.serialization.ObjectSchema<serializers.ChartPaneMetadata.Raw, StratifyX.ChartPaneMetadata>;
export declare namespace ChartPaneMetadata {
    interface Raw {
        yAxis: ChartYAxis.Raw[];
        series: SeriesInfo.Raw[];
        sessionRanges: SessionRange.Raw[];
    }
}
