/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const Color: core.serialization.Schema<serializers.Color.Raw, StratifyX.Color>;
export declare namespace Color {
    type Raw = "Default" | "Primary" | "Secondary" | "Success" | "Warning" | "Error" | "Info" | "Muted" | "Accent" | "Slate" | "Gray" | "Zinc" | "Neutral" | "Stone" | "Black" | "White" | "Blue" | "Sky" | "Cyan" | "Teal" | "Indigo" | "Violet" | "Purple" | "Red" | "Rose" | "Pink" | "Fuchsia" | "Orange" | "Amber" | "Yellow" | "Lime" | "Green" | "Emerald" | "Gold" | "Silver" | "Bronze";
}
