/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { MetaDataOption } from "./MetaDataOption";
import { VisibilitySelector } from "./VisibilitySelector";
export declare const CustomFieldsOption: core.serialization.ObjectSchema<serializers.CustomFieldsOption.Raw, StratifyX.CustomFieldsOption>;
export declare namespace CustomFieldsOption {
    interface Raw {
        fields: MetaDataOption.Raw[];
        visibility: VisibilitySelector.Raw[];
    }
}
