/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { AssetSpecificationData } from "./AssetSpecificationData";
import { TimeframeInfo } from "./TimeframeInfo";
export declare const DataInfoPerAsset: core.serialization.ObjectSchema<serializers.DataInfoPerAsset.Raw, StratifyX.DataInfoPerAsset>;
export declare namespace DataInfoPerAsset {
    interface Raw {
        asset: AssetSpecificationData.Raw;
        start_date: string;
        end_date: string;
        timeframes: TimeframeInfo.Raw[];
    }
}
