/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const ErrorResponse: core.serialization.ObjectSchema<serializers.ErrorResponse.Raw, StratifyX.ErrorResponse>;
export declare namespace ErrorResponse {
    interface Raw {
        error: string;
        message: string;
        timestamp: string;
        additionalContext?: Record<string, string> | null;
    }
}
