/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { AnyJson } from "./AnyJson";
export declare const EventContext: core.serialization.Schema<serializers.EventContext.Raw, StratifyX.EventContext>;
export declare namespace EventContext {
    type Raw = Record<string, AnyJson.Raw | null>;
}
