"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventMarkersMetadata = void 0;
const SelectorsMetadata_1 = require("./SelectorsMetadata");
exports.EventMarkersMetadata = SelectorsMetadata_1.SelectorsMetadata;
