/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { MetaDataOption } from "./MetaDataOption";
export declare const ExecutionCostMetaData: core.serialization.ObjectSchema<serializers.ExecutionCostMetaData.Raw, StratifyX.ExecutionCostMetaData>;
export declare namespace ExecutionCostMetaData {
    interface Raw {
        id: string;
        name?: string | null;
        description?: string | null;
        options?: MetaDataOption.Raw[] | null;
        tags?: string[] | null;
    }
}
