/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { ExecutionCostConfig } from "./ExecutionCostConfig";
export declare const ExecutionOptions: core.serialization.ObjectSchema<serializers.ExecutionOptions.Raw, StratifyX.ExecutionOptions>;
export declare namespace ExecutionOptions {
    interface Raw {
        cash: number;
        currency: string;
        slippage?: (ExecutionCostConfig.Raw | null) | null;
        commission?: (ExecutionCostConfig.Raw | null) | null;
    }
}
