/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { TableMetadataColumnDef } from "./TableMetadataColumnDef";
export declare const FullTableMetaData: core.serialization.ObjectSchema<serializers.FullTableMetaData.Raw, StratifyX.FullTableMetaData>;
export declare namespace FullTableMetaData {
    interface Raw {
        start_ts: number;
        start_ts_str: string;
        end_ts: number;
        end_ts_str: string;
        total_size: number;
        index_type: string;
        columns: TableMetadataColumnDef.Raw[];
    }
}
