/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { MetaDataOption } from "./MetaDataOption";
export declare const FuturesContinuationMetaData: core.serialization.ObjectSchema<serializers.FuturesContinuationMetaData.Raw, StratifyX.FuturesContinuationMetaData>;
export declare namespace FuturesContinuationMetaData {
    interface Raw {
        id: string;
        name?: string | null;
        description?: string | null;
        type?: string | null;
        params?: MetaDataOption.Raw[] | null;
        tags?: string[] | null;
    }
}
