/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { LifecycleEvent } from "./LifecycleEvent";
import { ProgressEvent } from "./ProgressEvent";
import { MetricEvent } from "./MetricEvent";
import { SummaryEvent } from "./SummaryEvent";
import { LogEvent } from "./LogEvent";
export declare const GenericEvent: core.serialization.Schema<serializers.GenericEvent.Raw, StratifyX.GenericEvent>;
export declare namespace GenericEvent {
    type Raw = LifecycleEvent.Raw | ProgressEvent.Raw | MetricEvent.Raw | SummaryEvent.Raw | LogEvent.Raw;
}
