/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const GenericAliasSpec: core.serialization.ObjectSchema<serializers.GenericAliasSpec.Raw, StratifyX.GenericAliasSpec>;
export declare namespace GenericAliasSpec {
    interface Raw {
        name: string;
        resolution: number;
        resolution_input_id: string;
    }
}
