/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const IndexConstituent: core.serialization.ObjectSchema<serializers.IndexConstituent.Raw, StratifyX.IndexConstituent>;
export declare namespace IndexConstituent {
    interface Raw {
        index?: string | null;
        constituents?: string[] | null;
        unsupported?: string[] | null;
    }
}
