/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { JobListItemStatus } from "./JobListItemStatus";
import { JobPeriod } from "./JobPeriod";
export declare const JobListItem: core.serialization.ObjectSchema<serializers.JobListItem.Raw, StratifyX.JobListItem>;
export declare namespace JobListItem {
    interface Raw {
        id: string;
        definition_id: string;
        status: JobListItemStatus.Raw;
        period?: (JobPeriod.Raw | null) | null;
        created_at: number;
    }
}
