/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { EventContext } from "./EventContext";
import { OperationStatus } from "./OperationStatus";
export declare const LifecycleEvent: core.serialization.ObjectSchema<serializers.LifecycleEvent.Raw, StratifyX.LifecycleEvent>;
export declare namespace LifecycleEvent {
    interface Raw {
        timestamp: number;
        path: string;
        context: EventContext.Raw;
        status: OperationStatus.Raw;
        operation_type: string;
        operation_name: string;
        duration?: (number | null) | null;
        error_message?: (string | null) | null;
        items_succeeded?: (number | null) | null;
        items_failed?: (number | null) | null;
        items_skipped?: (number | null) | null;
        items_total?: (number | null) | null;
    }
}
