/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const LineSpec: core.serialization.ObjectSchema<serializers.LineSpec.Raw, StratifyX.LineSpec>;
export declare namespace LineSpec {
    interface Raw {
        dataKey: string;
        name: string;
        color?: unknown | null;
        dashStyle?: unknown | null;
        lineWidth?: (number | null) | null;
        step?: boolean | null;
        enableMarkers?: boolean | null;
    }
}
