/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { Color } from "./Color";
import { DashStyle } from "./DashStyle";
import { LineInterpolation } from "./LineInterpolation";
export declare const LineSpec: core.serialization.ObjectSchema<serializers.LineSpec.Raw, StratifyX.LineSpec>;
export declare namespace LineSpec {
    interface Raw {
        dataKey: string;
        name: string;
        color?: Color.Raw | null;
        dashStyle?: DashStyle.Raw | null;
        lineWidth?: (number | null) | null;
        step?: boolean | null;
        enableMarkers?: boolean | null;
        priceScaleId?: (string | null) | null;
        interpolation?: LineInterpolation.Raw | null;
    }
}
