/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { EventContext } from "./EventContext";
import { LogLevel } from "./LogLevel";
export declare const LogEvent: core.serialization.ObjectSchema<serializers.LogEvent.Raw, StratifyX.LogEvent>;
export declare namespace LogEvent {
    interface Raw {
        timestamp: number;
        path: string;
        context: EventContext.Raw;
        level: LogLevel.Raw;
        message: string;
        source?: (string | null) | null;
    }
}
