/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const LogicalOperator: core.serialization.Schema<serializers.LogicalOperator.Raw, StratifyX.LogicalOperator>;
export declare namespace LogicalOperator {
    type Raw = "And" | "Or" | "Null";
}
