/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const LogLevel: core.serialization.Schema<serializers.LogLevel.Raw, StratifyX.LogLevel>;
export declare namespace LogLevel {
    type Raw = "debug" | "info" | "warn" | "error";
}
