/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { MetaDataArgRef } from "./MetaDataArgRef";
import { TimeOfDay } from "./TimeOfDay";
import { TimeDelta } from "./TimeDelta";
import { SessionTypeValue } from "./SessionTypeValue";
import { SessionAnchorValue } from "./SessionAnchorValue";
import { EventMarkerSchema } from "./EventMarkerSchema";
import { TableReportSchema } from "./TableReportSchema";
import { Sequence } from "./Sequence";
export declare const MetaDataOptionDefinition: core.serialization.Schema<serializers.MetaDataOptionDefinition.Raw, StratifyX.MetaDataOptionDefinition>;
export declare namespace MetaDataOptionDefinition {
    type Raw = number | boolean | string | MetaDataArgRef.Raw | TimeOfDay.Raw | TimeDelta.Raw | SessionTypeValue.Raw | SessionAnchorValue.Raw | EventMarkerSchema.Raw | TableReportSchema.Raw | Sequence.Raw;
}
