/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { MonteCarloStatusStatus } from "./MonteCarloStatusStatus";
export declare const MonteCarloStatus: core.serialization.ObjectSchema<serializers.MonteCarloStatus.Raw, StratifyX.MonteCarloStatus>;
export declare namespace MonteCarloStatus {
    interface Raw {
        id: string;
        status: MonteCarloStatusStatus.Raw;
        progress: number;
        error?: (string | null) | null;
        created_at: number;
        completed_at: number;
    }
}
