/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const NullPolicy: core.serialization.ObjectSchema<serializers.NullPolicy.Raw, StratifyX.NullPolicy>;
export declare namespace NullPolicy {
    interface Raw {
        input: string;
        output: string;
        constantValue?: (number | null) | null;
    }
}
