/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const OperationStatus: core.serialization.Schema<serializers.OperationStatus.Raw, StratifyX.OperationStatus>;
export declare namespace OperationStatus {
    type Raw = "pending" | "started" | "in_progress" | "completed" | "failed" | "cancelled" | "skipped";
}
