/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { ScalarJson } from "./ScalarJson";
export declare const OrderRow: core.serialization.ObjectSchema<serializers.OrderRow.Raw, StratifyX.OrderRow>;
export declare namespace OrderRow {
    interface Raw {
        index?: (ScalarJson.Raw | null) | null;
        asset?: (string | null) | null;
        updated_at?: (string | null) | null;
        status?: (string | null) | null;
        side?: (string | null) | null;
        type?: (string | null) | null;
        quantity?: (number | null) | null;
        filled_qty?: (number | null) | null;
        filled_price?: (number | null) | null;
        is_active?: (boolean | null) | null;
        limit_price?: (number | null) | null;
        stop_price?: (number | null) | null;
        id?: (string | null) | null;
        oca_group?: (string | null) | null;
        parent_id?: (string | null) | null;
        failure_reason?: (string | null) | null;
        commission?: (number | null) | null;
        slippage?: (number | null) | null;
        tif?: (string | null) | null;
        trail_amount?: (number | null) | null;
        hwm?: (number | null) | null;
    }
}
