/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const PaginationInfo: core.serialization.ObjectSchema<serializers.PaginationInfo.Raw, StratifyX.PaginationInfo>;
export declare namespace PaginationInfo {
    interface Raw {
        total: number;
        limit: number;
        offset: number;
        has_more: boolean;
    }
}
