/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { ArrowTableRows } from "./ArrowTableRows";
export declare const PaginatedTableResponse: core.serialization.ObjectSchema<serializers.PaginatedTableResponse.Raw, StratifyX.PaginatedTableResponse>;
export declare namespace PaginatedTableResponse {
    interface Raw {
        items: ArrowTableRows.Raw;
        page: number;
        total_pages: number;
    }
}
