/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { Color } from "./Color";
export declare const PlotBandSpec: core.serialization.ObjectSchema<serializers.PlotBandSpec.Raw, StratifyX.PlotBandSpec>;
export declare namespace PlotBandSpec {
    interface Raw {
        from: number;
        to: number;
        label?: (string | null) | null;
        color?: Color.Raw | null;
        opacity?: (number | null) | null;
    }
}
