/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const PolygonMetadata: core.serialization.ObjectSchema<serializers.PolygonMetadata.Raw, StratifyX.PolygonMetadata>;
export declare namespace PolygonMetadata {
    interface Raw {
        original_ticker?: (string | null) | null;
        type?: (string | null) | null;
        locale?: (string | null) | null;
        cik?: (string | null) | null;
        composite_figi?: (string | null) | null;
        last_updated?: (string | null) | null;
    }
}
