/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { ScalarJson } from "./ScalarJson";
export declare const PositionRow: core.serialization.ObjectSchema<serializers.PositionRow.Raw, StratifyX.PositionRow>;
export declare namespace PositionRow {
    interface Raw {
        index?: (ScalarJson.Raw | null) | null;
        asset?: (string | null) | null;
        quantity?: (number | null) | null;
        market_value?: (number | null) | null;
        current_price?: (number | null) | null;
        updated_at?: (string | null) | null;
        type?: (string | null) | null;
        fx_rate?: (number | null) | null;
    }
}
