/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const ScalarJson: core.serialization.Schema<serializers.ScalarJson.Raw, StratifyX.ScalarJson>;
export declare namespace ScalarJson {
    type Raw = number | string | boolean;
}
