/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { SelectorMeta } from "./SelectorMeta";
export declare const SelectorsMetadata: core.serialization.Schema<serializers.SelectorsMetadata.Raw, StratifyX.SelectorsMetadata>;
export declare namespace SelectorsMetadata {
    type Raw = Record<string, SelectorMeta.Raw[]>;
}
