/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const SelectorDataResponse: core.serialization.ObjectSchema<serializers.SelectorDataResponse.Raw, StratifyX.SelectorDataResponse>;
export declare namespace SelectorDataResponse {
    interface Raw {
        items: Record<string, unknown>[];
        total?: number | null;
        page?: number | null;
        page_size?: number | null;
    }
}
