/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { SequenceItem } from "./SequenceItem";
export declare const Sequence: core.serialization.Schema<serializers.Sequence.Raw, StratifyX.Sequence>;
export declare namespace Sequence {
    type Raw = SequenceItem.Raw[];
}
