/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { MetaDataArgDefinitionMapping } from "./MetaDataArgDefinitionMapping";
import { RenderingSchema } from "./RenderingSchema";
export declare const SeriesInfo: core.serialization.ObjectSchema<serializers.SeriesInfo.Raw, StratifyX.SeriesInfo>;
export declare namespace SeriesInfo {
    interface Raw {
        id: string;
        type: string;
        name: string;
        dataMapping: Record<string, string>;
        templateDataMapping: Record<string, string>;
        zIndex: number;
        yAxis: number;
        linkedTo?: (string | null) | null;
        configOptions: MetaDataArgDefinitionMapping.Raw;
        renderingSchema?: RenderingSchema.Raw | null;
    }
}
