/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const SessionAnchorValue: core.serialization.ObjectSchema<serializers.SessionAnchorValue.Raw, StratifyX.SessionAnchorValue>;
export declare namespace SessionAnchorValue {
    interface Raw {
        session_anchor: string;
    }
}
