/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { TimeOfDay } from "./TimeOfDay";
export declare const SessionRange: core.serialization.ObjectSchema<serializers.SessionRange.Raw, StratifyX.SessionRange>;
export declare namespace SessionRange {
    interface Raw {
        start: TimeOfDay.Raw;
        end: TimeOfDay.Raw;
    }
}
