/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const SessionSchema: core.serialization.ObjectSchema<serializers.SessionSchema.Raw, StratifyX.SessionSchema>;
export declare namespace SessionSchema {
    interface Raw {
        activeKey: string;
        highKey: string;
        lowKey: string;
        color?: unknown | null;
        opacity?: number | null;
        borderStyle?: unknown | null;
    }
}
