/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { DatePeriodConfig } from "./DatePeriodConfig";
export declare const StrategyConfigMetaData: core.serialization.ObjectSchema<serializers.StrategyConfigMetaData.Raw, StratifyX.StrategyConfigMetaData>;
export declare namespace StrategyConfigMetaData {
    interface Raw {
        allowedDateRange?: (DatePeriodConfig.Raw | null) | null;
        isIntradayOnly: boolean;
    }
}
