/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { DataOption } from "./DataOption";
import { StrategyConfigMetaData } from "./StrategyConfigMetaData";
export declare const StudyDefinition: core.serialization.ObjectSchema<serializers.StudyDefinition.Raw, StratifyX.StudyDefinition>;
export declare namespace StudyDefinition {
    interface Raw {
        name: string;
        description: string;
        data: DataOption.Raw;
        source: string;
        metadata?: (StrategyConfigMetaData.Raw | null) | null;
        global_timeframe?: string | null;
    }
}
