/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { EventContext } from "./EventContext";
export declare const SummaryEvent: core.serialization.ObjectSchema<serializers.SummaryEvent.Raw, StratifyX.SummaryEvent>;
export declare namespace SummaryEvent {
    interface Raw {
        timestamp: number;
        path: string;
        context: EventContext.Raw;
        overall_progress_percent: number;
        operations_completed: number;
        operations_total: number;
        operations_failed: number;
        operations_running: number;
        currently_running: string[];
        estimated_remaining?: (number | null) | null;
    }
}
