/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const TableColumnSchema: core.serialization.ObjectSchema<serializers.TableColumnSchema.Raw, StratifyX.TableColumnSchema>;
export declare namespace TableColumnSchema {
    interface Raw {
        column_id: string;
        title: string;
    }
}
