/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const TableMetadataColumnDef: core.serialization.ObjectSchema<serializers.TableMetadataColumnDef.Raw, StratifyX.TableMetadataColumnDef>;
export declare namespace TableMetadataColumnDef {
    interface Raw {
        name: string;
        type: string;
        null_count: number;
        true_count?: (number | null) | null;
        false_count?: (number | null) | null;
        minimum?: (number | null) | null;
        maximum?: (number | null) | null;
        unique_values: Record<string, number>;
    }
}
