/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const TableColumnMetadata: core.serialization.ObjectSchema<serializers.TableColumnMetadata.Raw, StratifyX.TableColumnMetadata>;
export declare namespace TableColumnMetadata {
    interface Raw {
        id: string;
        name?: string | null;
        type?: number | null;
    }
}
