/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { TableColumnSchema } from "./TableColumnSchema";
export declare const TableReportSchema: core.serialization.ObjectSchema<serializers.TableReportSchema.Raw, StratifyX.TableReportSchema>;
export declare namespace TableReportSchema {
    interface Raw {
        title: string;
        select_key: string;
        columns: TableColumnSchema.Raw[];
    }
}
