/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const TimeframeInfo: core.serialization.ObjectSchema<serializers.TimeframeInfo.Raw, StratifyX.TimeframeInfo>;
export declare namespace TimeframeInfo {
    interface Raw {
        timeframe: string;
        absolute_start_ms: number;
        absolute_end_ms: number;
        total_bars: number;
    }
}
