/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { TimeFrameItem } from "./TimeFrameItem";
import { CustomFieldsOption } from "./CustomFieldsOption";
export declare const TimeFrameSelectorItems: core.serialization.Schema<serializers.TimeFrameSelectorItems.Raw, StratifyX.TimeFrameSelectorItems>;
export declare namespace TimeFrameSelectorItems {
    type Raw = TimeFrameItem.Raw[] | CustomFieldsOption.Raw;
}
