/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { ChartPaneMetadata } from "./ChartPaneMetadata";
export declare const TimeFrameChartMetadata: core.serialization.Schema<serializers.TimeFrameChartMetadata.Raw, StratifyX.TimeFrameChartMetadata>;
export declare namespace TimeFrameChartMetadata {
    type Raw = Record<string, ChartPaneMetadata.Raw>;
}
