/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const TimeDelta: core.serialization.ObjectSchema<serializers.TimeDelta.Raw, StratifyX.TimeDelta>;
export declare namespace TimeDelta {
    interface Raw {
        days?: number | null;
        hours?: number | null;
        minutes?: number | null;
        seconds?: number | null;
        milliseconds?: number | null;
        microseconds?: number | null;
        weeks?: number | null;
    }
}
