/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
import { MetaDataOption } from "./MetaDataOption";
import { IoMetaData } from "./IoMetaData";
import { TupleOutputSpec } from "./TupleOutputSpec";
import { NullPolicy } from "./NullPolicy";
import { GenericAliasSpec } from "./GenericAliasSpec";
import { FlagSchema } from "./FlagSchema";
export declare const TransformsMetaData: core.serialization.ObjectSchema<serializers.TransformsMetaData.Raw, StratifyX.TransformsMetaData>;
export declare namespace TransformsMetaData {
    interface Raw {
        id: string;
        category?: string | null;
        plotKind?: string | null;
        name?: string | null;
        options?: MetaDataOption.Raw[] | null;
        isCrossSectional?: boolean | null;
        desc?: string | null;
        inputs?: IoMetaData.Raw[] | null;
        outputs?: IoMetaData.Raw[] | null;
        tuple_output_specs?: TupleOutputSpec.Raw[] | null;
        atLeastOneInputRequired?: boolean | null;
        tags?: string[] | null;
        requiresTimeFrame?: boolean | null;
        requiredDataSources?: string[] | null;
        intradayOnly?: boolean | null;
        nullPolicy?: NullPolicy.Raw | null;
        internalUse?: boolean | null;
        alias?: string | null;
        hasNullTransform?: boolean | null;
        visibility?: number | null;
        generic_alias?: (GenericAliasSpec.Raw | null) | null;
        flagSchema?: (FlagSchema.Raw | null) | null;
        strategyTypes?: string[] | null;
        relatedTransforms?: string[] | null;
        assetRequirements?: string[] | null;
        usageContext?: string | null;
        limitations?: string | null;
    }
}
