/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const TransformCategoryMetaData: core.serialization.ObjectSchema<serializers.TransformCategoryMetaData.Raw, StratifyX.TransformCategoryMetaData>;
export declare namespace TransformCategoryMetaData {
    interface Raw {
        category?: string | null;
        name: string;
        desc?: string | null;
    }
}
