/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as StratifyX from "../../api/index";
import * as core from "../../core";
export declare const VisibilitySelector: core.serialization.ObjectSchema<serializers.VisibilitySelector.Raw, StratifyX.VisibilitySelector>;
export declare namespace VisibilitySelector {
    interface Raw {
        timeframe_type: string;
        fields: string[];
    }
}
