/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "./environments";
import * as core from "./core";
import { Health } from "./api/resources/health/client/Client";
import { Metadata } from "./api/resources/metadata/client/Client";
import { ScriptValidation } from "./api/resources/scriptValidation/client/Client";
import { Documentation } from "./api/resources/documentation/client/Client";
import { Studies } from "./api/resources/studies/client/Client";
import { StudiesDefinitions } from "./api/resources/studiesDefinitions/client/Client";
import { StudiesExecutions } from "./api/resources/studiesExecutions/client/Client";
import { StudiesEvents } from "./api/resources/studiesEvents/client/Client";
import { StudiesTables } from "./api/resources/studiesTables/client/Client";
import { StudiesAnalytics } from "./api/resources/studiesAnalytics/client/Client";
import { StudiesPerformance } from "./api/resources/studiesPerformance/client/Client";
import { StudiesMetrics } from "./api/resources/studiesMetrics/client/Client";
import { StudiesAccount } from "./api/resources/studiesAccount/client/Client";
import { StudiesOrders } from "./api/resources/studiesOrders/client/Client";
import { StudiesPositions } from "./api/resources/studiesPositions/client/Client";
import { StudiesEventMarkers } from "./api/resources/studiesEventMarkers/client/Client";
import { StudiesMonteCarlo } from "./api/resources/studiesMonteCarlo/client/Client";
export declare namespace StratifyXClient {
    interface Options {
        environment?: core.Supplier<environments.StratifyXEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        fetcher?: core.FetchFunction;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class StratifyXClient {
    protected readonly _options: StratifyXClient.Options;
    protected _health: Health | undefined;
    protected _metadata: Metadata | undefined;
    protected _scriptValidation: ScriptValidation | undefined;
    protected _documentation: Documentation | undefined;
    protected _studies: Studies | undefined;
    protected _studiesDefinitions: StudiesDefinitions | undefined;
    protected _studiesExecutions: StudiesExecutions | undefined;
    protected _studiesEvents: StudiesEvents | undefined;
    protected _studiesTables: StudiesTables | undefined;
    protected _studiesAnalytics: StudiesAnalytics | undefined;
    protected _studiesPerformance: StudiesPerformance | undefined;
    protected _studiesMetrics: StudiesMetrics | undefined;
    protected _studiesAccount: StudiesAccount | undefined;
    protected _studiesOrders: StudiesOrders | undefined;
    protected _studiesPositions: StudiesPositions | undefined;
    protected _studiesEventMarkers: StudiesEventMarkers | undefined;
    protected _studiesMonteCarlo: StudiesMonteCarlo | undefined;
    constructor(_options?: StratifyXClient.Options);
    get health(): Health;
    get metadata(): Metadata;
    get scriptValidation(): ScriptValidation;
    get documentation(): Documentation;
    get studies(): Studies;
    get studiesDefinitions(): StudiesDefinitions;
    get studiesExecutions(): StudiesExecutions;
    get studiesEvents(): StudiesEvents;
    get studiesTables(): StudiesTables;
    get studiesAnalytics(): StudiesAnalytics;
    get studiesPerformance(): StudiesPerformance;
    get studiesMetrics(): StudiesMetrics;
    get studiesAccount(): StudiesAccount;
    get studiesOrders(): StudiesOrders;
    get studiesPositions(): StudiesPositions;
    get studiesEventMarkers(): StudiesEventMarkers;
    get studiesMonteCarlo(): StudiesMonteCarlo;
}
