"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.StratifyXEnvironment = void 0;
exports.StratifyXEnvironment = {
    Default: "http://localhost:9000",
};
