/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as StratifyX from "../../../../api/index";
import * as core from "../../../../core";
export declare const GetApiV1StudiesExecutionsExecutionIdPositionsRequestSortDirection: core.serialization.Schema<serializers.GetApiV1StudiesExecutionsExecutionIdPositionsRequestSortDirection.Raw, StratifyX.GetApiV1StudiesExecutionsExecutionIdPositionsRequestSortDirection>;
export declare namespace GetApiV1StudiesExecutionsExecutionIdPositionsRequestSortDirection {
    type Raw = "asc" | "desc";
}
