/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as StratifyX from "../../../../api/index";
import * as core from "../../../../core";
export declare const PostApiV1StudiesExecutionsExecutionIdPositionsFilteredRequestSortDirection: core.serialization.Schema<serializers.PostApiV1StudiesExecutionsExecutionIdPositionsFilteredRequestSortDirection.Raw, StratifyX.PostApiV1StudiesExecutionsExecutionIdPositionsFilteredRequestSortDirection>;
export declare namespace PostApiV1StudiesExecutionsExecutionIdPositionsFilteredRequestSortDirection {
    type Raw = "asc" | "desc";
}
