# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.metadata_response import MetadataResponse
from ..types.paginated_assets_response import PaginatedAssetsResponse
from .raw_client import AsyncRawMetadataClient, RawMetadataClient
from .types.get_api_v1metadata_method_request_method import GetApiV1MetadataMethodRequestMethod


class MetadataClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMetadataClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMetadataClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMetadataClient
        """
        return self._raw_client

    def get_asset_specifications_with_optional_pagination(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        query: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedAssetsResponse:
        """
        Returns asset specifications with optional pagination and search filtering.
        When no pagination parameters are provided, returns all assets.
        When `page` is specified, returns paginated results with metadata.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number (1-indexed). When omitted, returns all assets without pagination.

        page_size : typing.Optional[int]
            Number of items per page. Defaults to 100.

        query : typing.Optional[str]
            Search query to filter assets by ticker or name (case-insensitive).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedAssetsResponse
            Asset specifications

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.metadata.get_asset_specifications_with_optional_pagination()
        """
        _response = self._raw_client.get_asset_specifications_with_optional_pagination(
            page=page, page_size=page_size, query=query, request_options=request_options
        )
        return _response.data

    def get_ui_strategy_metadata_by_method(
        self, method: GetApiV1MetadataMethodRequestMethod, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MetadataResponse:
        """
        Returns a JSON payload (typically an array) that depends on `{method}`.
        Known valid methods include:
        - transforms
        - commission
        - epoch_folio_category
        - order
        - position
        - round_trip
        - futures_continuation
        - slippage
        - timeframes
        - transforms_category
        - assets
        - indices
        - index_constituents

        Parameters
        ----------
        method : GetApiV1MetadataMethodRequestMethod

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MetadataResponse
            Metadata JSON (method-dependent)

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.metadata.get_ui_strategy_metadata_by_method(
            method="transforms",
        )
        """
        _response = self._raw_client.get_ui_strategy_metadata_by_method(method, request_options=request_options)
        return _response.data


class AsyncMetadataClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMetadataClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMetadataClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMetadataClient
        """
        return self._raw_client

    async def get_asset_specifications_with_optional_pagination(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        query: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedAssetsResponse:
        """
        Returns asset specifications with optional pagination and search filtering.
        When no pagination parameters are provided, returns all assets.
        When `page` is specified, returns paginated results with metadata.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number (1-indexed). When omitted, returns all assets without pagination.

        page_size : typing.Optional[int]
            Number of items per page. Defaults to 100.

        query : typing.Optional[str]
            Search query to filter assets by ticker or name (case-insensitive).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedAssetsResponse
            Asset specifications

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.metadata.get_asset_specifications_with_optional_pagination()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_asset_specifications_with_optional_pagination(
            page=page, page_size=page_size, query=query, request_options=request_options
        )
        return _response.data

    async def get_ui_strategy_metadata_by_method(
        self, method: GetApiV1MetadataMethodRequestMethod, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MetadataResponse:
        """
        Returns a JSON payload (typically an array) that depends on `{method}`.
        Known valid methods include:
        - transforms
        - commission
        - epoch_folio_category
        - order
        - position
        - round_trip
        - futures_continuation
        - slippage
        - timeframes
        - transforms_category
        - assets
        - indices
        - index_constituents

        Parameters
        ----------
        method : GetApiV1MetadataMethodRequestMethod

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MetadataResponse
            Metadata JSON (method-dependent)

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.metadata.get_ui_strategy_metadata_by_method(
                method="transforms",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_ui_strategy_metadata_by_method(method, request_options=request_options)
        return _response.data
