"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetApiV1MetadataMethodRequestMethod = void 0;
exports.GetApiV1MetadataMethodRequestMethod = {
    Transforms: "transforms",
    Commission: "commission",
    EpochFolioCategory: "epoch_folio_category",
    Order: "order",
    Position: "position",
    RoundTrip: "round_trip",
    FuturesContinuation: "futures_continuation",
    Slippage: "slippage",
    Timeframes: "timeframes",
    TransformsCategory: "transforms_category",
    Assets: "assets",
    Indices: "indices",
    IndexConstituents: "index_constituents",
};
