/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type GetApiV1MetadataMethodRequestMethod = "transforms" | "commission" | "epoch_folio_category" | "order" | "position" | "round_trip" | "futures_continuation" | "slippage" | "timeframes" | "transforms_category" | "assets" | "indices" | "index_constituents";
export declare const GetApiV1MetadataMethodRequestMethod: {
    readonly Transforms: "transforms";
    readonly Commission: "commission";
    readonly EpochFolioCategory: "epoch_folio_category";
    readonly Order: "order";
    readonly Position: "position";
    readonly RoundTrip: "round_trip";
    readonly FuturesContinuation: "futures_continuation";
    readonly Slippage: "slippage";
    readonly Timeframes: "timeframes";
    readonly TransformsCategory: "transforms_category";
    readonly Assets: "assets";
    readonly Indices: "indices";
    readonly IndexConstituents: "index_constituents";
};
