/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as StratifyX from "../../../index";
export declare namespace StudiesDefinitions {
    interface Options {
        environment?: core.Supplier<environments.StratifyXEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        fetcher?: core.FetchFunction;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class StudiesDefinitions {
    protected readonly _options: StudiesDefinitions.Options;
    constructor(_options?: StudiesDefinitions.Options);
    /**
     * @param {StudiesDefinitions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     *
     * @example
     *     await client.studiesDefinitions.listStudyDefinitions()
     */
    listStudyDefinitions(requestOptions?: StudiesDefinitions.RequestOptions): core.HttpResponsePromise<string[]>;
    private __listStudyDefinitions;
    /**
     * @param {StratifyX.StudyDefinition} request
     * @param {StudiesDefinitions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     *
     * @example
     *     await client.studiesDefinitions.createStudyDefinition({
     *         name: "name",
     *         description: "description",
     *         data: {
     *             assets: ["assets"],
     *             source: "source"
     *         },
     *         source: "source"
     *     })
     */
    createStudyDefinition(request: StratifyX.StudyDefinition, requestOptions?: StudiesDefinitions.RequestOptions): core.HttpResponsePromise<StratifyX.IdResponse>;
    private __createStudyDefinition;
    /**
     * @param {string} definitionId
     * @param {StratifyX.GetApiV1StudiesDefinitionsDefinitionIdRequest} request
     * @param {StudiesDefinitions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     *
     * @example
     *     await client.studiesDefinitions.getAStudyDefinitionById("definitionId")
     */
    getAStudyDefinitionById(definitionId: string, request?: StratifyX.GetApiV1StudiesDefinitionsDefinitionIdRequest, requestOptions?: StudiesDefinitions.RequestOptions): core.HttpResponsePromise<StratifyX.StudyDefinition>;
    private __getAStudyDefinitionById;
    /**
     * @param {string} definitionId
     * @param {StratifyX.PutApiV1StudiesDefinitionsDefinitionIdRequest} request
     * @param {StudiesDefinitions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     *
     * @example
     *     await client.studiesDefinitions.updateAStudyDefinitionById("definitionId", {
     *         body: {
     *             name: "name",
     *             description: "description",
     *             data: {
     *                 assets: ["assets"],
     *                 source: "source"
     *             },
     *             source: "source"
     *         }
     *     })
     */
    updateAStudyDefinitionById(definitionId: string, request: StratifyX.PutApiV1StudiesDefinitionsDefinitionIdRequest, requestOptions?: StudiesDefinitions.RequestOptions): core.HttpResponsePromise<StratifyX.StudyDefinition>;
    private __updateAStudyDefinitionById;
    /**
     * Permanently deletes a study definition and performs a cascading delete of all associated executions (jobs). This operation cannot be undone. All execution results, logs, and analytics data for this study will be permanently removed.
     *
     * @param {string} definitionId
     * @param {StratifyX.DeleteApiV1StudiesDefinitionsDefinitionIdRequest} request
     * @param {StudiesDefinitions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     * @throws {@link StratifyX.NotFoundError}
     *
     * @example
     *     await client.studiesDefinitions.deleteAStudyDefinitionAndAllLinkedExecutions("definitionId")
     */
    deleteAStudyDefinitionAndAllLinkedExecutions(definitionId: string, request?: StratifyX.DeleteApiV1StudiesDefinitionsDefinitionIdRequest, requestOptions?: StudiesDefinitions.RequestOptions): core.HttpResponsePromise<StratifyX.MessageResponse>;
    private __deleteAStudyDefinitionAndAllLinkedExecutions;
    /**
     * Permanently deletes multiple study definitions and performs cascading delete of all associated executions (jobs) for each definition. This operation cannot be undone. All execution results, logs, and analytics data for these studies will be permanently removed. Nonexistent IDs are treated as successful (idempotent).
     *
     * @param {string[]} request
     * @param {StudiesDefinitions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     *
     * @example
     *     await client.studiesDefinitions.bulkDeleteStudyDefinitionsAndAllLinkedExecutions(["string"])
     */
    bulkDeleteStudyDefinitionsAndAllLinkedExecutions(request: string[], requestOptions?: StudiesDefinitions.RequestOptions): core.HttpResponsePromise<StratifyX.MessageResponse>;
    private __bulkDeleteStudyDefinitionsAndAllLinkedExecutions;
    /**
     * @param {string} definitionId
     * @param {StratifyX.GetApiV1StudiesDefinitionsDefinitionIdJobsRequest} request
     * @param {StudiesDefinitions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     * @throws {@link StratifyX.NotFoundError}
     *
     * @example
     *     await client.studiesDefinitions.listJobsForAStudyDefinition("definitionId")
     */
    listJobsForAStudyDefinition(definitionId: string, request?: StratifyX.GetApiV1StudiesDefinitionsDefinitionIdJobsRequest, requestOptions?: StudiesDefinitions.RequestOptions): core.HttpResponsePromise<StratifyX.JobListItem[]>;
    private __listJobsForAStudyDefinition;
    protected _getAuthorizationHeader(): Promise<string | undefined>;
}
