"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostApiV1StudiesExecutionsExecutionIdOrdersFilteredRequestSortDirection = void 0;
exports.PostApiV1StudiesExecutionsExecutionIdOrdersFilteredRequestSortDirection = {
    Asc: "asc",
    Desc: "desc",
};
