/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as StratifyX from "../../../../api/index";
import * as core from "../../../../core";
export declare const GetApiV1DocsNameRequestName: core.serialization.Schema<serializers.GetApiV1DocsNameRequestName.Raw, StratifyX.GetApiV1DocsNameRequestName>;
export declare namespace GetApiV1DocsNameRequestName {
    type Raw = "overview.md" | "script_grammar.ebnf" | "execution_guide.md" | "timeframe_guide.md" | "examples.txt";
}
