# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chart_base.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'chart_base.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63hart_base.proto\x12\x0b\x65poch_proto\x1a\x0c\x63ommon.proto\"n\n\x07\x41xisDef\x12(\n\x04type\x18\x01 \x01(\x0e\x32\x15.epoch_proto.AxisTypeH\x00\x88\x01\x01\x12\x12\n\x05label\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x12\n\ncategories\x18\x03 \x03(\tB\x07\n\x05_typeB\x08\n\x06_label\"\xd9\x01\n\x08\x43hartDef\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x34\n\x04type\x18\x03 \x01(\x0e\x32&.epoch_proto.EpochFolioDashboardWidget\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12)\n\x06y_axis\x18\x05 \x01(\x0b\x32\x14.epoch_proto.AxisDefH\x00\x88\x01\x01\x12)\n\x06x_axis\x18\x06 \x01(\x0b\x32\x14.epoch_proto.AxisDefH\x01\x88\x01\x01\x42\t\n\x07_y_axisB\t\n\x07_x_axis\"A\n\x0fStraightLineDef\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x10\n\x08vertical\x18\x03 \x01(\x08\"J\n\x04\x42\x61nd\x12!\n\x04\x66rom\x18\x01 \x01(\x0b\x32\x13.epoch_proto.Scalar\x12\x1f\n\x02to\x18\x02 \x01(\x0b\x32\x13.epoch_proto.Scalar\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x01\"$\n\x0cNumericPoint\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"\x9e\x01\n\x04Line\x12 \n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x12.epoch_proto.Point\x12\x0c\n\x04name\x18\x02 \x01(\t\x12/\n\ndash_style\x18\x03 \x01(\x0e\x32\x16.epoch_proto.DashStyleH\x00\x88\x01\x01\x12\x17\n\nline_width\x18\x04 \x01(\rH\x01\x88\x01\x01\x42\r\n\x0b_dash_styleB\r\n\x0b_line_width\"\xac\x01\n\x0bNumericLine\x12\'\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x19.epoch_proto.NumericPoint\x12\x0c\n\x04name\x18\x02 \x01(\t\x12/\n\ndash_style\x18\x03 \x01(\x0e\x32\x16.epoch_proto.DashStyleH\x00\x88\x01\x01\x12\x17\n\nline_width\x18\x04 \x01(\rH\x01\x88\x01\x01\x42\r\n\x0b_dash_styleB\r\n\x0b_line_width*P\n\tStackType\x12\x18\n\x14StackTypeUnspecified\x10\x00\x12\x13\n\x0fStackTypeNormal\x10\x01\x12\x14\n\x10StackTypePercent\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chart_base_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STACKTYPE']._serialized_start=927
  _globals['_STACKTYPE']._serialized_end=1007
  _globals['_AXISDEF']._serialized_start=47
  _globals['_AXISDEF']._serialized_end=157
  _globals['_CHARTDEF']._serialized_start=160
  _globals['_CHARTDEF']._serialized_end=377
  _globals['_STRAIGHTLINEDEF']._serialized_start=379
  _globals['_STRAIGHTLINEDEF']._serialized_end=444
  _globals['_BAND']._serialized_start=446
  _globals['_BAND']._serialized_end=520
  _globals['_POINT']._serialized_start=522
  _globals['_POINT']._serialized_end=551
  _globals['_NUMERICPOINT']._serialized_start=553
  _globals['_NUMERICPOINT']._serialized_end=589
  _globals['_LINE']._serialized_start=592
  _globals['_LINE']._serialized_end=750
  _globals['_NUMERICLINE']._serialized_start=753
  _globals['_NUMERICLINE']._serialized_end=925
# @@protoc_insertion_point(module_scope)
