# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: errorbar_chart.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'errorbar_chart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import chart_base_pb2 as chart__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65rrorbar_chart.proto\x12\x0b\x65poch_proto\x1a\x10\x63hart_base.proto\"5\n\rErrorBarPoint\x12\t\n\x01x\x18\x01 \x01(\x03\x12\x0b\n\x03low\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\"<\n\x14NumericErrorBarPoint\x12\t\n\x01x\x18\x01 \x01(\x01\x12\x0b\n\x03low\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\"\xa4\x01\n\x0e\x45rrorBarSeries\x12\x0c\n\x04name\x18\x01 \x01(\t\x12(\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x1a.epoch_proto.ErrorBarPoint\x12\x1a\n\rwhisker_color\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x1a\n\rwhisker_width\x18\x04 \x01(\rH\x01\x88\x01\x01\x42\x10\n\x0e_whisker_colorB\x10\n\x0e_whisker_width\"\xb2\x01\n\x15NumericErrorBarSeries\x12\x0c\n\x04name\x18\x01 \x01(\t\x12/\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32!.epoch_proto.NumericErrorBarPoint\x12\x1a\n\rwhisker_color\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x1a\n\rwhisker_width\x18\x04 \x01(\rH\x01\x88\x01\x01\x42\x10\n\x0e_whisker_colorB\x10\n\x0e_whisker_width\"\x9d\x01\n\x0b\x45rrorBarDef\x12(\n\tchart_def\x18\x01 \x01(\x0b\x32\x15.epoch_proto.ChartDef\x12+\n\x06series\x18\x02 \x03(\x0b\x32\x1b.epoch_proto.ErrorBarSeries\x12)\n\tbase_line\x18\x03 \x01(\x0b\x32\x11.epoch_proto.LineH\x00\x88\x01\x01\x42\x0c\n\n_base_line\"\xb2\x01\n\x12NumericErrorBarDef\x12(\n\tchart_def\x18\x01 \x01(\x0b\x32\x15.epoch_proto.ChartDef\x12\x32\n\x06series\x18\x02 \x03(\x0b\x32\".epoch_proto.NumericErrorBarSeries\x12\x30\n\tbase_line\x18\x03 \x01(\x0b\x32\x18.epoch_proto.NumericLineH\x00\x88\x01\x01\x42\x0c\n\n_base_lineb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'errorbar_chart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORBARPOINT']._serialized_start=55
  _globals['_ERRORBARPOINT']._serialized_end=108
  _globals['_NUMERICERRORBARPOINT']._serialized_start=110
  _globals['_NUMERICERRORBARPOINT']._serialized_end=170
  _globals['_ERRORBARSERIES']._serialized_start=173
  _globals['_ERRORBARSERIES']._serialized_end=337
  _globals['_NUMERICERRORBARSERIES']._serialized_start=340
  _globals['_NUMERICERRORBARSERIES']._serialized_end=518
  _globals['_ERRORBARDEF']._serialized_start=521
  _globals['_ERRORBARDEF']._serialized_end=678
  _globals['_NUMERICERRORBARDEF']._serialized_start=681
  _globals['_NUMERICERRORBARDEF']._serialized_end=859
# @@protoc_insertion_point(module_scope)
