# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: heatmap_chart.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'heatmap_chart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import chart_base_pb2 as chart__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13heatmap_chart.proto\x12\x0b\x65poch_proto\x1a\x10\x63hart_base.proto\"3\n\x0cHeatMapPoint\x12\t\n\x01x\x18\x01 \x01(\x04\x12\t\n\x01y\x18\x02 \x01(\x04\x12\r\n\x05value\x18\x03 \x01(\x01\"a\n\nHeatMapDef\x12(\n\tchart_def\x18\x01 \x01(\x0b\x32\x15.epoch_proto.ChartDef\x12)\n\x06points\x18\x02 \x03(\x0b\x32\x19.epoch_proto.HeatMapPointb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heatmap_chart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEATMAPPOINT']._serialized_start=54
  _globals['_HEATMAPPOINT']._serialized_end=105
  _globals['_HEATMAPDEF']._serialized_start=107
  _globals['_HEATMAPDEF']._serialized_end=204
# @@protoc_insertion_point(module_scope)
