# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: histogram_chart.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'histogram_chart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import chart_base_pb2 as chart__base__pb2
from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15histogram_chart.proto\x12\x0b\x65poch_proto\x1a\x10\x63hart_base.proto\x1a\x0c\x63ommon.proto\"\xb8\x01\n\x0cHistogramDef\x12(\n\tchart_def\x18\x01 \x01(\x0b\x32\x15.epoch_proto.ChartDef\x12 \n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x12.epoch_proto.Array\x12\x34\n\x0estraight_lines\x18\x03 \x03(\x0b\x32\x1c.epoch_proto.StraightLineDef\x12\x17\n\nbins_count\x18\x04 \x01(\rH\x00\x88\x01\x01\x42\r\n\x0b_bins_countb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'histogram_chart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HISTOGRAMDEF']._serialized_start=71
  _globals['_HISTOGRAMDEF']._serialized_end=255
# @@protoc_insertion_point(module_scope)
