# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scatter_chart.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'scatter_chart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import chart_base_pb2 as chart__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13scatter_chart.proto\x12\x0b\x65poch_proto\x1a\x10\x63hart_base.proto\"^\n\x0cScatterPoint\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x11\n\x04name\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05\x63olor\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_nameB\x08\n\x06_color\"d\n\rScatterSeries\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x19.epoch_proto.ScatterPoint\x12\x12\n\x05\x63olor\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_color\"\x98\x01\n\nScatterDef\x12(\n\tchart_def\x18\x01 \x01(\x0b\x32\x15.epoch_proto.ChartDef\x12*\n\x06series\x18\x02 \x03(\x0b\x32\x1a.epoch_proto.ScatterSeries\x12\x34\n\x0estraight_lines\x18\x03 \x03(\x0b\x32\x1c.epoch_proto.StraightLineDefb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scatter_chart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCATTERPOINT']._serialized_start=54
  _globals['_SCATTERPOINT']._serialized_end=148
  _globals['_SCATTERSERIES']._serialized_start=150
  _globals['_SCATTERSERIES']._serialized_end=250
  _globals['_SCATTERDEF']._serialized_start=253
  _globals['_SCATTERDEF']._serialized_end=405
# @@protoc_insertion_point(module_scope)
