# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xrange_chart.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'xrange_chart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import chart_base_pb2 as chart__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12xrange_chart.proto\x12\x0b\x65poch_proto\x1a\x10\x63hart_base.proto\"@\n\x0bXRangePoint\x12\t\n\x01x\x18\x01 \x01(\x03\x12\n\n\x02x2\x18\x02 \x01(\x03\x12\t\n\x01y\x18\x03 \x01(\x04\x12\x0f\n\x07is_long\x18\x04 \x01(\x08\"s\n\tXRangeDef\x12(\n\tchart_def\x18\x01 \x01(\x0b\x32\x15.epoch_proto.ChartDef\x12\x12\n\ncategories\x18\x02 \x03(\t\x12(\n\x06points\x18\x03 \x03(\x0b\x32\x18.epoch_proto.XRangePointb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xrange_chart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_XRANGEPOINT']._serialized_start=53
  _globals['_XRANGEPOINT']._serialized_end=117
  _globals['_XRANGEDEF']._serialized_start=119
  _globals['_XRANGEDEF']._serialized_end=234
# @@protoc_insertion_point(module_scope)
