# This file was auto-generated by Fern from our API Definition.

import typing

GetApiV1MetadataMethodRequestMethod = typing.Union[
    typing.Literal[
        "transforms",
        "commission",
        "epoch_folio_category",
        "order",
        "position",
        "round_trip",
        "futures_continuation",
        "slippage",
        "timeframes",
        "transforms_category",
        "assets",
        "indices",
        "index_constituents",
    ],
    typing.Any,
]
