# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.tear_sheet_metadata_response import TearSheetMetadataResponse
from .raw_client import AsyncRawStudiesPerformanceClient, RawStudiesPerformanceClient


class StudiesPerformanceClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawStudiesPerformanceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawStudiesPerformanceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStudiesPerformanceClient
        """
        return self._raw_client

    def get_performance_metadata(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TearSheetMetadataResponse:
        """
        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TearSheetMetadataResponse
            Performance metadata JSON

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.studies_performance.get_performance_metadata(
            execution_id="executionId",
        )
        """
        _response = self._raw_client.get_performance_metadata(execution_id, request_options=request_options)
        return _response.data

    def get_performance_report_file(
        self,
        execution_id: str,
        *,
        category: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[bytes]:
        """
        Parameters
        ----------
        execution_id : str

        category : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            Performance report file (format depends on server)

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.studies_performance.get_performance_report_file(
            execution_id="executionId",
        )
        """
        with self._raw_client.get_performance_report_file(
            execution_id, category=category, request_options=request_options
        ) as r:
            yield from r.data


class AsyncStudiesPerformanceClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawStudiesPerformanceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawStudiesPerformanceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStudiesPerformanceClient
        """
        return self._raw_client

    async def get_performance_metadata(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TearSheetMetadataResponse:
        """
        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TearSheetMetadataResponse
            Performance metadata JSON

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.studies_performance.get_performance_metadata(
                execution_id="executionId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_performance_metadata(execution_id, request_options=request_options)
        return _response.data

    async def get_performance_report_file(
        self,
        execution_id: str,
        *,
        category: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[bytes]:
        """
        Parameters
        ----------
        execution_id : str

        category : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            Performance report file (format depends on server)

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.studies_performance.get_performance_report_file(
                execution_id="executionId",
            )


        asyncio.run(main())
        """
        async with self._raw_client.get_performance_report_file(
            execution_id, category=category, request_options=request_options
        ) as r:
            async for _chunk in r.data:
                yield _chunk
