# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..types.error_response import ErrorResponse
from ..types.event_markers_metadata import EventMarkersMetadata
from ..types.paginated_table_response import PaginatedTableResponse
from ..types.table_filter_metadata import TableFilterMetadata
from .types.get_api_v1studies_executions_execution_id_event_markers_request_sort_direction import (
    GetApiV1StudiesExecutionsExecutionIdEventMarkersRequestSortDirection,
)


class RawStudiesEventMarkersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_event_marker_metadata(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[EventMarkersMetadata]:
        """
        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EventMarkersMetadata]
            Metadata JSON
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/event-markers/metadata",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EventMarkersMetadata,
                    parse_obj_as(
                        type_=EventMarkersMetadata,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_event_marker_filter_metadata(
        self,
        execution_id: str,
        *,
        asset_id: typing.Optional[str] = None,
        index: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TableFilterMetadata]:
        """
        Parameters
        ----------
        execution_id : str

        asset_id : typing.Optional[str]

        index : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TableFilterMetadata]
            Filter metadata JSON
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/event-markers/filter-metadata",
            method="GET",
            params={
                "asset_id": asset_id,
                "index": index,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TableFilterMetadata,
                    parse_obj_as(
                        type_=TableFilterMetadata,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_event_markers_tabular_json(
        self,
        execution_id: str,
        *,
        asset_id: typing.Optional[str] = None,
        index: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        sort_key: typing.Optional[str] = None,
        sort_direction: typing.Optional[GetApiV1StudiesExecutionsExecutionIdEventMarkersRequestSortDirection] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaginatedTableResponse]:
        """
        Parameters
        ----------
        execution_id : str

        asset_id : typing.Optional[str]

        index : typing.Optional[int]

        page : typing.Optional[int]

        sort_key : typing.Optional[str]

        sort_direction : typing.Optional[GetApiV1StudiesExecutionsExecutionIdEventMarkersRequestSortDirection]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaginatedTableResponse]
            Paginated event markers response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/event-markers",
            method="GET",
            params={
                "asset_id": asset_id,
                "index": index,
                "page": page,
                "sort_key": sort_key,
                "sort_direction": sort_direction,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedTableResponse,
                    parse_obj_as(
                        type_=PaginatedTableResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawStudiesEventMarkersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_event_marker_metadata(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[EventMarkersMetadata]:
        """
        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EventMarkersMetadata]
            Metadata JSON
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/event-markers/metadata",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EventMarkersMetadata,
                    parse_obj_as(
                        type_=EventMarkersMetadata,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_event_marker_filter_metadata(
        self,
        execution_id: str,
        *,
        asset_id: typing.Optional[str] = None,
        index: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TableFilterMetadata]:
        """
        Parameters
        ----------
        execution_id : str

        asset_id : typing.Optional[str]

        index : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TableFilterMetadata]
            Filter metadata JSON
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/event-markers/filter-metadata",
            method="GET",
            params={
                "asset_id": asset_id,
                "index": index,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TableFilterMetadata,
                    parse_obj_as(
                        type_=TableFilterMetadata,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_event_markers_tabular_json(
        self,
        execution_id: str,
        *,
        asset_id: typing.Optional[str] = None,
        index: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        sort_key: typing.Optional[str] = None,
        sort_direction: typing.Optional[GetApiV1StudiesExecutionsExecutionIdEventMarkersRequestSortDirection] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaginatedTableResponse]:
        """
        Parameters
        ----------
        execution_id : str

        asset_id : typing.Optional[str]

        index : typing.Optional[int]

        page : typing.Optional[int]

        sort_key : typing.Optional[str]

        sort_direction : typing.Optional[GetApiV1StudiesExecutionsExecutionIdEventMarkersRequestSortDirection]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaginatedTableResponse]
            Paginated event markers response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/event-markers",
            method="GET",
            params={
                "asset_id": asset_id,
                "index": index,
                "page": page,
                "sort_key": sort_key,
                "sort_direction": sort_direction,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedTableResponse,
                    parse_obj_as(
                        type_=PaginatedTableResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
