# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.generic_event import GenericEvent
from ..types.id_response import IdResponse
from ..types.message_response import MessageResponse
from ..types.monte_carlo_status import MonteCarloStatus
from ..types.monte_carlo_status_list import MonteCarloStatusList
from .raw_client import AsyncRawStudiesMonteCarloClient, RawStudiesMonteCarloClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class StudiesMonteCarloClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawStudiesMonteCarloClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawStudiesMonteCarloClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStudiesMonteCarloClient
        """
        return self._raw_client

    def list_monte_carlo_simulations_for_an_execution(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MonteCarloStatusList:
        """
        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonteCarloStatusList
            Monte Carlo list JSON

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.studies_monte_carlo.list_monte_carlo_simulations_for_an_execution(
            execution_id="executionId",
        )
        """
        _response = self._raw_client.list_monte_carlo_simulations_for_an_execution(
            execution_id, request_options=request_options
        )
        return _response.data

    def start_a_monte_carlo_simulation_for_an_execution(
        self,
        execution_id: str,
        *,
        n_bootstrap: typing.Optional[int] = OMIT,
        confidence_level: typing.Optional[float] = OMIT,
        enable_bayesian: typing.Optional[bool] = OMIT,
        mcmc_samples: typing.Optional[int] = OMIT,
        mcmc_burnin: typing.Optional[int] = OMIT,
        analyze_sharpe: typing.Optional[bool] = OMIT,
        analyze_sortino: typing.Optional[bool] = OMIT,
        analyze_max_drawdown: typing.Optional[bool] = OMIT,
        analyze_returns: typing.Optional[bool] = OMIT,
        generate_cone: typing.Optional[bool] = OMIT,
        cone_days_forward: typing.Optional[int] = OMIT,
        cone_percentiles: typing.Optional[typing.Sequence[float]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IdResponse:
        """
        Parameters
        ----------
        execution_id : str

        n_bootstrap : typing.Optional[int]

        confidence_level : typing.Optional[float]

        enable_bayesian : typing.Optional[bool]

        mcmc_samples : typing.Optional[int]

        mcmc_burnin : typing.Optional[int]

        analyze_sharpe : typing.Optional[bool]

        analyze_sortino : typing.Optional[bool]

        analyze_max_drawdown : typing.Optional[bool]

        analyze_returns : typing.Optional[bool]

        generate_cone : typing.Optional[bool]

        cone_days_forward : typing.Optional[int]

        cone_percentiles : typing.Optional[typing.Sequence[float]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IdResponse
            Started

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.studies_monte_carlo.start_a_monte_carlo_simulation_for_an_execution(
            execution_id="executionId",
        )
        """
        _response = self._raw_client.start_a_monte_carlo_simulation_for_an_execution(
            execution_id,
            n_bootstrap=n_bootstrap,
            confidence_level=confidence_level,
            enable_bayesian=enable_bayesian,
            mcmc_samples=mcmc_samples,
            mcmc_burnin=mcmc_burnin,
            analyze_sharpe=analyze_sharpe,
            analyze_sortino=analyze_sortino,
            analyze_max_drawdown=analyze_max_drawdown,
            analyze_returns=analyze_returns,
            generate_cone=generate_cone,
            cone_days_forward=cone_days_forward,
            cone_percentiles=cone_percentiles,
            request_options=request_options,
        )
        return _response.data

    def get_monte_carlo_simulation_status(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MonteCarloStatus:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonteCarloStatus
            Status JSON

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.studies_monte_carlo.get_monte_carlo_simulation_status(
            execution_id="executionId",
            mc_id="mcId",
        )
        """
        _response = self._raw_client.get_monte_carlo_simulation_status(
            execution_id, mc_id, request_options=request_options
        )
        return _response.data

    def get_monte_carlo_tearsheet_file(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[bytes]:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            Tearsheet file (protobuf)

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.studies_monte_carlo.get_monte_carlo_tearsheet_file(
            execution_id="executionId",
            mc_id="mcId",
        )
        """
        with self._raw_client.get_monte_carlo_tearsheet_file(execution_id, mc_id, request_options=request_options) as r:
            yield from r.data

    def delete_monte_carlo_simulation(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageResponse:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Deleted

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.studies_monte_carlo.delete_monte_carlo_simulation(
            execution_id="executionId",
            mc_id="mcId",
        )
        """
        _response = self._raw_client.delete_monte_carlo_simulation(execution_id, mc_id, request_options=request_options)
        return _response.data

    def get_monte_carlo_events(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[GenericEvent]:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GenericEvent]
            JSON array of events

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.studies_monte_carlo.get_monte_carlo_events(
            execution_id="executionId",
            mc_id="mcId",
        )
        """
        _response = self._raw_client.get_monte_carlo_events(execution_id, mc_id, request_options=request_options)
        return _response.data

    def stream_monte_carlo_events_sse(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.studies_monte_carlo.stream_monte_carlo_events_sse(
            execution_id="executionId",
            mc_id="mcId",
        )
        """
        _response = self._raw_client.stream_monte_carlo_events_sse(execution_id, mc_id, request_options=request_options)
        return _response.data


class AsyncStudiesMonteCarloClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawStudiesMonteCarloClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawStudiesMonteCarloClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStudiesMonteCarloClient
        """
        return self._raw_client

    async def list_monte_carlo_simulations_for_an_execution(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MonteCarloStatusList:
        """
        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonteCarloStatusList
            Monte Carlo list JSON

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.studies_monte_carlo.list_monte_carlo_simulations_for_an_execution(
                execution_id="executionId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_monte_carlo_simulations_for_an_execution(
            execution_id, request_options=request_options
        )
        return _response.data

    async def start_a_monte_carlo_simulation_for_an_execution(
        self,
        execution_id: str,
        *,
        n_bootstrap: typing.Optional[int] = OMIT,
        confidence_level: typing.Optional[float] = OMIT,
        enable_bayesian: typing.Optional[bool] = OMIT,
        mcmc_samples: typing.Optional[int] = OMIT,
        mcmc_burnin: typing.Optional[int] = OMIT,
        analyze_sharpe: typing.Optional[bool] = OMIT,
        analyze_sortino: typing.Optional[bool] = OMIT,
        analyze_max_drawdown: typing.Optional[bool] = OMIT,
        analyze_returns: typing.Optional[bool] = OMIT,
        generate_cone: typing.Optional[bool] = OMIT,
        cone_days_forward: typing.Optional[int] = OMIT,
        cone_percentiles: typing.Optional[typing.Sequence[float]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IdResponse:
        """
        Parameters
        ----------
        execution_id : str

        n_bootstrap : typing.Optional[int]

        confidence_level : typing.Optional[float]

        enable_bayesian : typing.Optional[bool]

        mcmc_samples : typing.Optional[int]

        mcmc_burnin : typing.Optional[int]

        analyze_sharpe : typing.Optional[bool]

        analyze_sortino : typing.Optional[bool]

        analyze_max_drawdown : typing.Optional[bool]

        analyze_returns : typing.Optional[bool]

        generate_cone : typing.Optional[bool]

        cone_days_forward : typing.Optional[int]

        cone_percentiles : typing.Optional[typing.Sequence[float]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IdResponse
            Started

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.studies_monte_carlo.start_a_monte_carlo_simulation_for_an_execution(
                execution_id="executionId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start_a_monte_carlo_simulation_for_an_execution(
            execution_id,
            n_bootstrap=n_bootstrap,
            confidence_level=confidence_level,
            enable_bayesian=enable_bayesian,
            mcmc_samples=mcmc_samples,
            mcmc_burnin=mcmc_burnin,
            analyze_sharpe=analyze_sharpe,
            analyze_sortino=analyze_sortino,
            analyze_max_drawdown=analyze_max_drawdown,
            analyze_returns=analyze_returns,
            generate_cone=generate_cone,
            cone_days_forward=cone_days_forward,
            cone_percentiles=cone_percentiles,
            request_options=request_options,
        )
        return _response.data

    async def get_monte_carlo_simulation_status(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MonteCarloStatus:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonteCarloStatus
            Status JSON

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.studies_monte_carlo.get_monte_carlo_simulation_status(
                execution_id="executionId",
                mc_id="mcId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_monte_carlo_simulation_status(
            execution_id, mc_id, request_options=request_options
        )
        return _response.data

    async def get_monte_carlo_tearsheet_file(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            Tearsheet file (protobuf)

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.studies_monte_carlo.get_monte_carlo_tearsheet_file(
                execution_id="executionId",
                mc_id="mcId",
            )


        asyncio.run(main())
        """
        async with self._raw_client.get_monte_carlo_tearsheet_file(
            execution_id, mc_id, request_options=request_options
        ) as r:
            async for _chunk in r.data:
                yield _chunk

    async def delete_monte_carlo_simulation(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageResponse:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Deleted

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.studies_monte_carlo.delete_monte_carlo_simulation(
                execution_id="executionId",
                mc_id="mcId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_monte_carlo_simulation(
            execution_id, mc_id, request_options=request_options
        )
        return _response.data

    async def get_monte_carlo_events(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[GenericEvent]:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GenericEvent]
            JSON array of events

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.studies_monte_carlo.get_monte_carlo_events(
                execution_id="executionId",
                mc_id="mcId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_monte_carlo_events(execution_id, mc_id, request_options=request_options)
        return _response.data

    async def stream_monte_carlo_events_sse(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.studies_monte_carlo.stream_monte_carlo_events_sse(
                execution_id="executionId",
                mc_id="mcId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.stream_monte_carlo_events_sse(
            execution_id, mc_id, request_options=request_options
        )
        return _response.data
