# This file was auto-generated by Fern from our API Definition.

import contextlib
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..types.error_response import ErrorResponse
from ..types.generic_event import GenericEvent
from ..types.id_response import IdResponse
from ..types.message_response import MessageResponse
from ..types.monte_carlo_status import MonteCarloStatus
from ..types.monte_carlo_status_list import MonteCarloStatusList

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawStudiesMonteCarloClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_monte_carlo_simulations_for_an_execution(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[MonteCarloStatusList]:
        """
        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MonteCarloStatusList]
            Monte Carlo list JSON
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/monte-carlo",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MonteCarloStatusList,
                    parse_obj_as(
                        type_=MonteCarloStatusList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def start_a_monte_carlo_simulation_for_an_execution(
        self,
        execution_id: str,
        *,
        n_bootstrap: typing.Optional[int] = OMIT,
        confidence_level: typing.Optional[float] = OMIT,
        enable_bayesian: typing.Optional[bool] = OMIT,
        mcmc_samples: typing.Optional[int] = OMIT,
        mcmc_burnin: typing.Optional[int] = OMIT,
        analyze_sharpe: typing.Optional[bool] = OMIT,
        analyze_sortino: typing.Optional[bool] = OMIT,
        analyze_max_drawdown: typing.Optional[bool] = OMIT,
        analyze_returns: typing.Optional[bool] = OMIT,
        generate_cone: typing.Optional[bool] = OMIT,
        cone_days_forward: typing.Optional[int] = OMIT,
        cone_percentiles: typing.Optional[typing.Sequence[float]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[IdResponse]:
        """
        Parameters
        ----------
        execution_id : str

        n_bootstrap : typing.Optional[int]

        confidence_level : typing.Optional[float]

        enable_bayesian : typing.Optional[bool]

        mcmc_samples : typing.Optional[int]

        mcmc_burnin : typing.Optional[int]

        analyze_sharpe : typing.Optional[bool]

        analyze_sortino : typing.Optional[bool]

        analyze_max_drawdown : typing.Optional[bool]

        analyze_returns : typing.Optional[bool]

        generate_cone : typing.Optional[bool]

        cone_days_forward : typing.Optional[int]

        cone_percentiles : typing.Optional[typing.Sequence[float]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IdResponse]
            Started
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/monte-carlo",
            method="POST",
            json={
                "n_bootstrap": n_bootstrap,
                "confidence_level": confidence_level,
                "enable_bayesian": enable_bayesian,
                "mcmc_samples": mcmc_samples,
                "mcmc_burnin": mcmc_burnin,
                "analyze_sharpe": analyze_sharpe,
                "analyze_sortino": analyze_sortino,
                "analyze_max_drawdown": analyze_max_drawdown,
                "analyze_returns": analyze_returns,
                "generate_cone": generate_cone,
                "cone_days_forward": cone_days_forward,
                "cone_percentiles": cone_percentiles,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IdResponse,
                    parse_obj_as(
                        type_=IdResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_monte_carlo_simulation_status(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[MonteCarloStatus]:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MonteCarloStatus]
            Status JSON
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/monte-carlo/{jsonable_encoder(mc_id)}/status",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MonteCarloStatus,
                    parse_obj_as(
                        type_=MonteCarloStatus,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    @contextlib.contextmanager
    def get_monte_carlo_tearsheet_file(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[HttpResponse[typing.Iterator[bytes]]]:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[HttpResponse[typing.Iterator[bytes]]]
            Tearsheet file (protobuf)
        """
        with self._client_wrapper.httpx_client.stream(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/monte-carlo/{jsonable_encoder(mc_id)}",
            method="GET",
            request_options=request_options,
        ) as _response:

            def _stream() -> HttpResponse[typing.Iterator[bytes]]:
                try:
                    if 200 <= _response.status_code < 300:
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return HttpResponse(
                            response=_response, data=(_chunk for _chunk in _response.iter_bytes(chunk_size=_chunk_size))
                        )
                    _response.read()
                    if _response.status_code == 400:
                        raise BadRequestError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                ErrorResponse,
                                parse_obj_as(
                                    type_=ErrorResponse,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                    )
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

            yield _stream()

    def delete_monte_carlo_simulation(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[MessageResponse]:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MessageResponse]
            Deleted
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/monte-carlo/{jsonable_encoder(mc_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageResponse,
                    parse_obj_as(
                        type_=MessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_monte_carlo_events(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.List[GenericEvent]]:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[GenericEvent]]
            JSON array of events
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/monte-carlo/{jsonable_encoder(mc_id)}/events",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[GenericEvent],
                    parse_obj_as(
                        type_=typing.List[GenericEvent],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def stream_monte_carlo_events_sse(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/monte-carlo/{jsonable_encoder(mc_id)}/events/stream",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawStudiesMonteCarloClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_monte_carlo_simulations_for_an_execution(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[MonteCarloStatusList]:
        """
        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MonteCarloStatusList]
            Monte Carlo list JSON
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/monte-carlo",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MonteCarloStatusList,
                    parse_obj_as(
                        type_=MonteCarloStatusList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def start_a_monte_carlo_simulation_for_an_execution(
        self,
        execution_id: str,
        *,
        n_bootstrap: typing.Optional[int] = OMIT,
        confidence_level: typing.Optional[float] = OMIT,
        enable_bayesian: typing.Optional[bool] = OMIT,
        mcmc_samples: typing.Optional[int] = OMIT,
        mcmc_burnin: typing.Optional[int] = OMIT,
        analyze_sharpe: typing.Optional[bool] = OMIT,
        analyze_sortino: typing.Optional[bool] = OMIT,
        analyze_max_drawdown: typing.Optional[bool] = OMIT,
        analyze_returns: typing.Optional[bool] = OMIT,
        generate_cone: typing.Optional[bool] = OMIT,
        cone_days_forward: typing.Optional[int] = OMIT,
        cone_percentiles: typing.Optional[typing.Sequence[float]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[IdResponse]:
        """
        Parameters
        ----------
        execution_id : str

        n_bootstrap : typing.Optional[int]

        confidence_level : typing.Optional[float]

        enable_bayesian : typing.Optional[bool]

        mcmc_samples : typing.Optional[int]

        mcmc_burnin : typing.Optional[int]

        analyze_sharpe : typing.Optional[bool]

        analyze_sortino : typing.Optional[bool]

        analyze_max_drawdown : typing.Optional[bool]

        analyze_returns : typing.Optional[bool]

        generate_cone : typing.Optional[bool]

        cone_days_forward : typing.Optional[int]

        cone_percentiles : typing.Optional[typing.Sequence[float]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IdResponse]
            Started
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/monte-carlo",
            method="POST",
            json={
                "n_bootstrap": n_bootstrap,
                "confidence_level": confidence_level,
                "enable_bayesian": enable_bayesian,
                "mcmc_samples": mcmc_samples,
                "mcmc_burnin": mcmc_burnin,
                "analyze_sharpe": analyze_sharpe,
                "analyze_sortino": analyze_sortino,
                "analyze_max_drawdown": analyze_max_drawdown,
                "analyze_returns": analyze_returns,
                "generate_cone": generate_cone,
                "cone_days_forward": cone_days_forward,
                "cone_percentiles": cone_percentiles,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IdResponse,
                    parse_obj_as(
                        type_=IdResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_monte_carlo_simulation_status(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[MonteCarloStatus]:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MonteCarloStatus]
            Status JSON
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/monte-carlo/{jsonable_encoder(mc_id)}/status",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MonteCarloStatus,
                    parse_obj_as(
                        type_=MonteCarloStatus,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    @contextlib.asynccontextmanager
    async def get_monte_carlo_tearsheet_file(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[bytes]]]:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[bytes]]]
            Tearsheet file (protobuf)
        """
        async with self._client_wrapper.httpx_client.stream(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/monte-carlo/{jsonable_encoder(mc_id)}",
            method="GET",
            request_options=request_options,
        ) as _response:

            async def _stream() -> AsyncHttpResponse[typing.AsyncIterator[bytes]]:
                try:
                    if 200 <= _response.status_code < 300:
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return AsyncHttpResponse(
                            response=_response,
                            data=(_chunk async for _chunk in _response.aiter_bytes(chunk_size=_chunk_size)),
                        )
                    await _response.aread()
                    if _response.status_code == 400:
                        raise BadRequestError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                ErrorResponse,
                                parse_obj_as(
                                    type_=ErrorResponse,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                    )
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

            yield await _stream()

    async def delete_monte_carlo_simulation(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[MessageResponse]:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MessageResponse]
            Deleted
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/monte-carlo/{jsonable_encoder(mc_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageResponse,
                    parse_obj_as(
                        type_=MessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_monte_carlo_events(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.List[GenericEvent]]:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[GenericEvent]]
            JSON array of events
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/monte-carlo/{jsonable_encoder(mc_id)}/events",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[GenericEvent],
                    parse_obj_as(
                        type_=typing.List[GenericEvent],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def stream_monte_carlo_events_sse(
        self, execution_id: str, mc_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Parameters
        ----------
        execution_id : str

        mc_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/studies/executions/{jsonable_encoder(execution_id)}/monte-carlo/{jsonable_encoder(mc_id)}/events/stream",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
