/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Algorithm metadata (see `epoch_script::strategy::AlgorithmBaseMetaData`)
 */
export interface AlgorithmBaseMetaData {
    id: string;
    name?: string;
    options?: StratifyX.MetaDataOption[];
    desc?: string;
    tags?: string[];
}
