/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Arbitrary JSON value (shape is server-defined)
 */
export type AnyJson = Record<string, unknown> | unknown[] | string | number | number | boolean;
