"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AssetSpecificationAssetClass = void 0;
exports.AssetSpecificationAssetClass = {
    Stocks: "Stocks",
    Fx: "FX",
    Crypto: "Crypto",
    Futures: "Futures",
    Indices: "Indices",
};
