/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Asset class type
 */
export type AssetSpecificationDataAssetClass = "Stocks" | "FX" | "Crypto" | "Futures" | "Indices";
export declare const AssetSpecificationDataAssetClass: {
    readonly Stocks: "Stocks";
    readonly Fx: "FX";
    readonly Crypto: "Crypto";
    readonly Futures: "Futures";
    readonly Indices: "Indices";
};
