/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Asset specification (see `data_sdk::asset::AssetSpecificationData`)
 */
export interface AssetSpecificationData {
    id: string;
    name?: string;
    ticker?: string;
    /** Asset class type */
    assetClass?: StratifyX.AssetSpecificationDataAssetClass;
    exchange?: string;
    currency?: string;
    industry?: string | null;
    sector?: string | null;
    multiplier?: number | null;
    minTick?: number | null;
    category?: string | null;
    eodStart?: string | null;
    eodEnd?: string | null;
    minuteStart?: string | null;
    minuteEnd?: string | null;
    expiryMonths?: string | null;
    /** MarketDataVendor enum (e.g. Archive, Polygon) */
    vendor?: string | null;
    polygonMetadata?: StratifyX.PolygonMetadata | null;
    lastUpdated?: string | null;
    dataSource?: string | null;
}
