/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Box rendering schema for FVG, Order Blocks, Gaps, Liquidity zones
 */
export interface BoxSchema {
    /** Column name for index/timestamp data */
    indexColumn?: string;
    /** Column name for box top */
    topKey: string;
    /** Column name for box bottom */
    bottomKey: string;
    /** Column name for signal (triggers box creation) */
    signalKey?: string;
    /** Column name for box end index (null = extend) */
    endIndexKey?: string;
    bullColor?: StratifyX.Color;
    bearColor?: StratifyX.Color;
    opacity?: number;
    showLabel?: boolean;
    /** Empty = use PlotKind name */
    labelText?: string;
}
