/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Candlestick (OHLCV) specification embedded in GenericSchema
 */
export interface CandlestickSpec {
    openKey?: string;
    highKey?: string;
    lowKey?: string;
    closeKey?: string;
    volumeKey?: string | null;
    upColor?: StratifyX.Color;
    downColor?: StratifyX.Color;
}
