/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Card column schema (see `epoch_script::CardColumnSchema`)
 */
export interface CardColumnSchema {
    columnId: string;
    slot: string;
    renderType: string;
    /** Maps colors to lists of values that trigger that color */
    colorMap: Record<string, (StratifyX.ScalarJson | null)[]>;
    label?: string | null;
}
