/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Category metadata (see `epoch_folio::CategoryMetaData`)
 */
export interface CategoryMetaData {
    value?: string;
    label?: string;
    description?: string;
}
