/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
export interface ChartPaneMetadata {
    yAxis: StratifyX.ChartYAxis[];
    series: StratifyX.SeriesInfo[];
    sessionRanges: StratifyX.SessionRange[];
}
