"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Color = void 0;
exports.Color = {
    Default: "Default",
    Primary: "Primary",
    Secondary: "Secondary",
    Success: "Success",
    Warning: "Warning",
    Error: "Error",
    Info: "Info",
    Muted: "Muted",
    Accent: "Accent",
    Slate: "Slate",
    Gray: "Gray",
    Zinc: "Zinc",
    Neutral: "Neutral",
    Stone: "Stone",
    Black: "Black",
    White: "White",
    Blue: "Blue",
    Sky: "Sky",
    Cyan: "Cyan",
    Teal: "Teal",
    Indigo: "Indigo",
    Violet: "Violet",
    Purple: "Purple",
    Red: "Red",
    Rose: "Rose",
    Pink: "Pink",
    Fuchsia: "Fuchsia",
    Orange: "Orange",
    Amber: "Amber",
    Yellow: "Yellow",
    Lime: "Lime",
    Green: "Green",
    Emerald: "Emerald",
    Gold: "Gold",
    Silver: "Silver",
    Bronze: "Bronze",
};
