"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ColumnFilterMetadataType = void 0;
exports.ColumnFilterMetadataType = {
    String: "string",
    Boolean: "boolean",
    Datetime: "datetime",
    Decimal: "decimal",
    Monetary: "monetary",
    Percent: "percent",
    Duration: "duration",
};
