/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
export interface DataInfoPerAsset {
    asset: StratifyX.AssetSpecificationData;
    startDate: Date;
    endDate: Date;
    timeframes: StratifyX.TimeframeInfo[];
}
