/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Error response (see `epoch_core::ErrorContext`, emitted via `epoch_stratifyx::server::SendError`)
 */
export interface ErrorResponse {
    /** Machine-readable error type */
    error: string;
    /** Human-readable error message */
    message: string;
    /** ISO-8601 UTC timestamp (no timezone suffix) */
    timestamp: string;
    /** Additional structured context (string map) */
    additionalContext?: Record<string, string>;
}
