/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Backtest execution options (see `epoch_stratifyx::ExecutionOptions`)
 */
export interface ExecutionOptions {
    cash: number;
    /** CountryCurrency enum (e.g. USD) */
    currency: string;
    slippage?: StratifyX.ExecutionCostConfig | null;
    commission?: StratifyX.ExecutionCostConfig | null;
}
