/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Hierarchical execution cost configuration (see `epoch_stratifyx::ExecutionCostConfig<T>`)
 */
export interface ExecutionCostConfig {
    model?: StratifyX.TemplatedGenericFunction | null;
    defaultModel?: StratifyX.TemplatedGenericFunction | null;
    assetClassOverrides?: Record<string, StratifyX.TemplatedGenericFunction>;
    symbolOverrides?: Record<string, StratifyX.TemplatedGenericFunction>;
}
