/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Execution cost metadata for slippage/commission models
 */
export interface ExecutionCostMetaData {
    id: string;
    name?: string;
    description?: string;
    options?: StratifyX.MetaDataOption[];
    tags?: string[];
}
