"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.FilterOperator = void 0;
exports.FilterOperator = {
    Equals: "Equals",
    NotEquals: "NotEquals",
    GreaterThan: "GreaterThan",
    GreaterThanOrEqual: "GreaterThanOrEqual",
    LessThan: "LessThan",
    LessThanOrEqual: "LessThanOrEqual",
    Contains: "Contains",
    NotContains: "NotContains",
    Between: "Between",
    NotBetween: "NotBetween",
    Null: "Null",
};
