/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Filter operator (see `epoch_core::FilterOperator`)
 */
export type FilterOperator = "Equals" | "NotEquals" | "GreaterThan" | "GreaterThanOrEqual" | "LessThan" | "LessThanOrEqual" | "Contains" | "NotContains" | "Between" | "NotBetween" | "Null";
export declare const FilterOperator: {
    readonly Equals: "Equals";
    readonly NotEquals: "NotEquals";
    readonly GreaterThan: "GreaterThan";
    readonly GreaterThanOrEqual: "GreaterThanOrEqual";
    readonly LessThan: "LessThan";
    readonly LessThanOrEqual: "LessThanOrEqual";
    readonly Contains: "Contains";
    readonly NotContains: "NotContains";
    readonly Between: "Between";
    readonly NotBetween: "NotBetween";
    readonly Null: "Null";
};
