/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Flag plot schema (see `epoch_script::transforms::FlagSchema`)
 */
export interface FlagSchema {
    icon: string;
    text: string;
    textIsTemplate: boolean;
    color: string;
    title?: string | null;
    valueKey: string;
}
