/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Full table metadata for a single (timeframe, asset) table (see `api::v1::FullTableMetaData`)
 */
export interface FullTableMetaData {
    /** Start timestamp (nanoseconds) */
    startTs: number;
    startTsStr: string;
    /** End timestamp (nanoseconds) */
    endTs: number;
    endTsStr: string;
    totalSize: number;
    indexType: string;
    columns: StratifyX.TableMetadataColumnDef[];
}
