/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Generic event (variant of Lifecycle/Progress/Metric/Summary/Log)
 */
export type GenericEvent = StratifyX.LifecycleEvent | StratifyX.ProgressEvent | StratifyX.MetricEvent | StratifyX.SummaryEvent | StratifyX.LogEvent;
