/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Generic alias resolution spec (see `epoch_script::transforms::GenericAliasSpec`)
 */
export interface GenericAliasSpec {
    name: string;
    /** GenericResolutionType enum: 0=ByFirstInput,1=ByBranchInput,2=ByOutputType */
    resolution: number;
    resolutionInputId: string;
}
