/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Generic rendering schema for indicators (lines, scatter, columns, etc.)
 */
export interface GenericSchema {
    lines?: StratifyX.LineSpec[];
    hLines?: StratifyX.HLineSpec[];
    scatter?: StratifyX.ScatterSpec[];
    columns?: StratifyX.ColumnSpec[];
    areaRanges?: StratifyX.AreaRangeSpec[];
    plotBands?: StratifyX.PlotBandSpec[];
    separatePanel?: boolean;
    yMin?: number | null;
    yMax?: number | null;
}
