/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
export interface HLineSpec {
    y: number;
    label?: string | null;
    color?: StratifyX.Color;
    dashStyle?: StratifyX.DashStyle;
    lineWidth?: number | null;
}
