/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Index constituents entry (see `data_sdk::asset::IndexConstituent`)
 */
export interface IndexConstituent {
    index?: string;
    constituents?: string[];
    unsupported?: string[];
}
