/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Transform IO metadata (see `epoch_script::transforms::IOMetaData`)
 */
export interface IoMetaData {
    type?: string;
    id: string;
    name?: string;
    optional?: boolean;
}
