/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Job/execution list item (see `epoch_stratifyx::server::JobListItem`)
 */
export interface JobListItem {
    id: string;
    definitionId: string;
    /** pending, running, completed, failed, cancelled */
    status: StratifyX.JobListItemStatus;
    period?: StratifyX.JobPeriod | null;
    /** Unix timestamp in milliseconds */
    createdAt: number;
}
