/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
export interface LifecycleEvent {
    /** Unix timestamp in milliseconds (system_clock) */
    timestamp: number;
    /** Event path (string form) */
    path: string;
    context: StratifyX.EventContext;
    status: StratifyX.OperationStatus;
    operationType: string;
    operationName: string;
    /** Duration in milliseconds */
    duration?: number | null;
    errorMessage?: string | null;
    itemsSucceeded?: number | null;
    itemsFailed?: number | null;
    itemsSkipped?: number | null;
    itemsTotal?: number | null;
}
