/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
export interface LogEvent {
    timestamp: number;
    path: string;
    context: StratifyX.EventContext;
    level: StratifyX.LogLevel;
    message: string;
    source?: string | null;
}
