/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Logical operator (see `epoch_core::LogicalOperator`)
 */
export type LogicalOperator = "And" | "Or" | "Null";
export declare const LogicalOperator: {
    readonly And: "And";
    readonly Or: "Or";
    readonly Null: "Null";
};
