"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MetaDataOptionType = void 0;
exports.MetaDataOptionType = {
    Integer: "Integer",
    Decimal: "Decimal",
    Boolean: "Boolean",
    Select: "Select",
    NumericList: "NumericList",
    StringList: "StringList",
    Time: "Time",
    Duration: "Duration",
    Session: "Session",
    SessionAnchor: "SessionAnchor",
    String: "String",
    EventMarkerSchema: "EventMarkerSchema",
    SqlStatement: "SqlStatement",
    TableReportSchema: "TableReportSchema",
    Null: "Null",
};
