/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * MetaDataOptionDefinition (variant; see `epoch_script::MetaDataOptionDefinition`)
 */
export type MetaDataOptionDefinition = number | boolean | string | StratifyX.MetaDataArgRef | StratifyX.TimeOfDay | StratifyX.TimeDelta | StratifyX.SessionTypeValue | StratifyX.SessionAnchorValue | StratifyX.EventMarkerSchema | StratifyX.TableReportSchema | StratifyX.Sequence;
