/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
export interface MetricEvent {
    timestamp: number;
    path: string;
    context: StratifyX.EventContext;
    metricName: string;
    value: number;
    unit?: string | null;
    minValue?: number | null;
    maxValue?: number | null;
}
