/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Monte Carlo simulation status (see `epoch_stratifyx::server::MonteCarloStatus`)
 */
export interface MonteCarloStatus {
    id: string;
    status: StratifyX.MonteCarloStatusStatus;
    progress: number;
    error?: string | null;
    createdAt: number;
    completedAt: number;
}
