"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MonteCarloStatusStatus = void 0;
exports.MonteCarloStatusStatus = {
    Pending: "pending",
    Running: "running",
    Completed: "completed",
    Failed: "failed",
    Cancelled: "cancelled",
};
