/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Null handling policy (see `epoch_core::NullPolicy`)
 */
export interface NullPolicy {
    input: string;
    output: string;
    constantValue?: number | null;
}
