/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Operation lifecycle status
 */
export type OperationStatus = "pending" | "started" | "in_progress" | "completed" | "failed" | "cancelled" | "skipped";
export declare const OperationStatus: {
    readonly Pending: "pending";
    readonly Started: "started";
    readonly InProgress: "in_progress";
    readonly Completed: "completed";
    readonly Failed: "failed";
    readonly Cancelled: "cancelled";
    readonly Skipped: "skipped";
};
