/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Order row (JSON-encoded Arrow table row; columns match `GetOrderTableHeader()` + index)
 */
export interface OrderRow {
    index?: StratifyX.ScalarJson | null;
    asset?: string | null;
    updatedAt?: Date | null;
    status?: string | null;
    side?: string | null;
    type?: string | null;
    quantity?: number | null;
    filledQty?: number | null;
    filledPrice?: number | null;
    isActive?: boolean | null;
    limitPrice?: number | null;
    stopPrice?: number | null;
    id?: string | null;
    ocaGroup?: string | null;
    parentId?: string | null;
    failureReason?: string | null;
    commission?: number | null;
    slippage?: number | null;
    tif?: string | null;
    trailAmount?: number | null;
    hwm?: number | null;
}
