/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Pagination metadata
 */
export interface PaginationInfo {
    /** Total number of items */
    total: number;
    /** Limit used for this request */
    limit: number;
    /** Offset used for this request */
    offset: number;
    /** Whether there are more items after this page */
    hasMore: boolean;
}
