/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Paginated response for tabular data
 */
export interface PaginatedTableResponse {
    items: StratifyX.ArrowTableRows;
    /** Current page number (0-indexed) */
    page: number;
    /** Total number of pages */
    totalPages: number;
}
