/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Union type covering all PlotKind rendering schemas
 */
export type RenderingSchema = StratifyX.GenericSchema | StratifyX.BoxSchema | StratifyX.TrendlineSchema | StratifyX.SessionSchema | StratifyX.ZoneSchema | StratifyX.CandlestickSchema;
