/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
export interface ScatterSpec {
    dataKey: string;
    name: string;
    color?: StratifyX.Color;
    symbol?: StratifyX.MarkerSymbol;
    radius?: number | null;
    /** Custom price scale (e.g., 'volume' for volume overlays) */
    priceScaleId?: string | null;
}
