/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface ScatterSpec {
    dataKey: string;
    name: string;
    color?: unknown;
    symbol?: unknown;
    radius?: number | null;
}
