/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Paginated selector/trade data response
 */
export interface SelectorDataResponse {
    /** Array of selector records (e.g., round trips, trade details) */
    items: Record<string, unknown>[];
    /** Total number of records available */
    total?: number;
    /** Current page number */
    page?: number;
    /** Number of items per page */
    pageSize?: number;
}
