/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Selector metadata entry (from selectors_metadata.json)
 */
export interface SelectorMeta {
    title: string;
    icon: string;
    schemas: StratifyX.CardColumnSchema[];
    pivotIndex: number | null;
}
