/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
export interface SeriesInfo {
    id: string;
    type: string;
    name: string;
    dataMapping: Record<string, string>;
    templateDataMapping: Record<string, string>;
    zIndex: number;
    yAxis: number;
    linkedTo?: string | null;
    configOptions: StratifyX.MetaDataArgDefinitionMapping;
}
