/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Study list item (see `epoch_stratifyx::server::StudyListItem`)
 */
export interface StudyListItem {
    id: string;
    name: string;
    description: string;
    assets: string[];
    /** Unix timestamp in milliseconds */
    createdAt: number;
    /** Unix timestamp in milliseconds */
    updatedAt: number;
    jobCount: number;
}
