/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Column metadata for table inspection (see `api::v1::ColumnDef`)
 */
export interface TableMetadataColumnDef {
    name: string;
    /** Arrow type string (e.g. int64, float64, string, timestamp[ns, tz=UTC]) */
    type: string;
    nullCount: number;
    trueCount?: number | null;
    falseCount?: number | null;
    minimum?: number | null;
    maximum?: number | null;
    uniqueValues: Record<string, number>;
}
