/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Tearsheet metadata response (see StrategyPerfService::GetMetadata)
 */
export interface TearSheetMetadataResponse {
    tearsheetMetadata: Record<string, StratifyX.TearSheetComponentCounts>;
    selectorMetadata?: StratifyX.SelectorsMetadata | null;
}
