/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Templated generic function configuration (see `epoch_script::strategy::TemplatedGenericFunction<T>`)
 */
export interface TemplatedGenericFunction {
    /** Algorithm/model type identifier */
    type: string;
    args: StratifyX.MetaDataArgDefinitionMapping;
}
