/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface TimeOfDay {
    hour?: number;
    minute?: number;
    second?: number;
    microsecond?: number;
    tz?: string;
}
