/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Trade analytics chart metadata (see `epoch_stratifyx::TradeAnalyticsChartMetaData`)
 */
export interface TradeAnalyticsChartMetaData {
    assetInfo: Record<string, StratifyX.DataInfoPerAsset>;
    chartInfo: StratifyX.TimeFrameChartMetadata;
}
