/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Trendline rendering schema for BOS/CHOCH, chart patterns
 */
export interface TrendlineSchema {
    signalKey?: string;
    levelKey: string;
    endIndexKey: string;
    bullColor?: unknown;
    bearColor?: unknown;
    dashStyle?: unknown;
    lineWidth?: number;
    showLabel?: boolean;
}
