/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../index";
/**
 * Zone rendering schema for time-based background zones
 */
export interface ZoneSchema {
    /** Column name for index/timestamp data */
    indexColumn?: string;
    /** Boolean column for zone active */
    valueKey: string;
    color?: StratifyX.Color;
    opacity?: number;
    /** 'background', 'top', or 'bottom' */
    position?: string;
}
