# This file was auto-generated by Fern from our API Definition.

import typing

GetApiV1StudiesExecutionsExecutionIdEventMarkersRequestSortDirection = typing.Union[
    typing.Literal["asc", "desc"], typing.Any
]
