"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.StratifyXTimeoutError = void 0;
class StratifyXTimeoutError extends Error {
    constructor(message) {
        super(message);
        Object.setPrototypeOf(this, StratifyXTimeoutError.prototype);
    }
}
exports.StratifyXTimeoutError = StratifyXTimeoutError;
