/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface GetApiV1MetadataAssetsRequest {
    /**
     * Page number (1-indexed). When omitted, returns all assets without pagination.
     */
    page?: number;
    /**
     * Number of items per page. Defaults to 100.
     */
    pageSize?: number;
    /**
     * Search query to filter assets by ticker or name (case-insensitive).
     */
    query?: string;
}
