/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as StratifyX from "../../../../index";
/**
 * @example
 *     {}
 */
export interface GetApiV1StudiesExecutionsExecutionIdEventMarkersRequest {
    assetId?: string;
    index?: number;
    page?: number;
    sortKey?: string;
    sortDirection?: StratifyX.GetApiV1StudiesExecutionsExecutionIdEventMarkersRequestSortDirection;
}
