/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as StratifyX from "../../../index";
import * as stream from "stream";
export declare namespace StudiesAnalytics {
    interface Options {
        environment?: core.Supplier<environments.StratifyXEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        fetcher?: core.FetchFunction;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class StudiesAnalytics {
    protected readonly _options: StudiesAnalytics.Options;
    constructor(_options?: StudiesAnalytics.Options);
    /**
     * @param {string} executionId
     * @param {StratifyX.GetApiV1StudiesExecutionsExecutionIdAnalyticsMetadataRequest} request
     * @param {StudiesAnalytics.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     *
     * @example
     *     await client.studiesAnalytics.getAnalyticsMetadata("executionId")
     */
    getAnalyticsMetadata(executionId: string, request?: StratifyX.GetApiV1StudiesExecutionsExecutionIdAnalyticsMetadataRequest, requestOptions?: StudiesAnalytics.RequestOptions): core.HttpResponsePromise<StratifyX.TradeAnalyticsChartMetaData>;
    private __getAnalyticsMetadata;
    /**
     * @throws {@link StratifyX.BadRequestError}
     */
    getAnalyticsAsArrowStream(executionId: string, request?: StratifyX.GetApiV1StudiesExecutionsExecutionIdAnalyticsRequest, requestOptions?: StudiesAnalytics.RequestOptions): core.HttpResponsePromise<stream.Readable>;
    private __getAnalyticsAsArrowStream;
    protected _getAuthorizationHeader(): Promise<string | undefined>;
}
