# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawDocumentationClient, RawDocumentationClient
from .types.get_api_v1docs_name_request_name import GetApiV1DocsNameRequestName
from .types.get_api_v1docs_response import GetApiV1DocsResponse


class DocumentationClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDocumentationClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDocumentationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDocumentationClient
        """
        return self._raw_client

    def list_available_documentation_files(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetApiV1DocsResponse:
        """
        Returns a list of available documentation files that can be retrieved via /api/v1/docs/{name}

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetApiV1DocsResponse
            List of available documents

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.documentation.list_available_documentation_files()
        """
        _response = self._raw_client.list_available_documentation_files(request_options=request_options)
        return _response.data

    def get_documentation_file_content(
        self, name: GetApiV1DocsNameRequestName, *, request_options: typing.Optional[RequestOptions] = None
    ) -> str:
        """
        Retrieves the content of a specific documentation file. Available files:
        - `overview.md` - Platform overview and capabilities
        - `script_grammar.ebnf` - EpochScript grammar specification
        - `execution_guide.md` - Strategy execution guide
        - `timeframe_guide.md` - Timeframe usage guide
        - `examples.txt` - Strategy code examples (joined from individual example files)

        Parameters
        ----------
        name : GetApiV1DocsNameRequestName
            Document filename

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        str
            Document content

        Examples
        --------
        from stratifyx import StratifyX

        client = StratifyX(
            token="YOUR_TOKEN",
        )
        client.documentation.get_documentation_file_content(
            name="overview.md",
        )
        """
        _response = self._raw_client.get_documentation_file_content(name, request_options=request_options)
        return _response.data


class AsyncDocumentationClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDocumentationClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDocumentationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDocumentationClient
        """
        return self._raw_client

    async def list_available_documentation_files(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetApiV1DocsResponse:
        """
        Returns a list of available documentation files that can be retrieved via /api/v1/docs/{name}

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetApiV1DocsResponse
            List of available documents

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.documentation.list_available_documentation_files()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_available_documentation_files(request_options=request_options)
        return _response.data

    async def get_documentation_file_content(
        self, name: GetApiV1DocsNameRequestName, *, request_options: typing.Optional[RequestOptions] = None
    ) -> str:
        """
        Retrieves the content of a specific documentation file. Available files:
        - `overview.md` - Platform overview and capabilities
        - `script_grammar.ebnf` - EpochScript grammar specification
        - `execution_guide.md` - Strategy execution guide
        - `timeframe_guide.md` - Timeframe usage guide
        - `examples.txt` - Strategy code examples (joined from individual example files)

        Parameters
        ----------
        name : GetApiV1DocsNameRequestName
            Document filename

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        str
            Document content

        Examples
        --------
        import asyncio

        from stratifyx import AsyncStratifyX

        client = AsyncStratifyX(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.documentation.get_documentation_file_content(
                name="overview.md",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_documentation_file_content(name, request_options=request_options)
        return _response.data
