/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as StratifyX from "../../../index";
export declare namespace StudiesEvents {
    interface Options {
        environment?: core.Supplier<environments.StratifyXEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        fetcher?: core.FetchFunction;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class StudiesEvents {
    protected readonly _options: StudiesEvents.Options;
    constructor(_options?: StudiesEvents.Options);
    /**
     * Server-Sent Events stream providing real-time execution updates including progress, lifecycle events, logs, and metrics. This is the primary endpoint for monitoring execution status.
     *
     * @param {string} executionId
     * @param {StratifyX.GetApiV1StudiesExecutionsExecutionIdStreamRequest} request
     * @param {StudiesEvents.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     *
     * @example
     *     await client.studiesEvents.unifiedEventStreamSse("executionId")
     */
    unifiedEventStreamSse(executionId: string, request?: StratifyX.GetApiV1StudiesExecutionsExecutionIdStreamRequest, requestOptions?: StudiesEvents.RequestOptions): core.HttpResponsePromise<void>;
    private __unifiedEventStreamSse;
    /**
     * Returns log events only (not lifecycle/progress/metric events) from persistent storage with pagination support.
     *
     * @param {string} executionId
     * @param {StratifyX.GetApiV1StudiesExecutionsExecutionIdLogsRequest} request
     * @param {StudiesEvents.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     *
     * @example
     *     await client.studiesEvents.getExecutionLogsWithPagination("executionId")
     */
    getExecutionLogsWithPagination(executionId: string, request?: StratifyX.GetApiV1StudiesExecutionsExecutionIdLogsRequest, requestOptions?: StudiesEvents.RequestOptions): core.HttpResponsePromise<StratifyX.PaginatedLogsResponse>;
    private __getExecutionLogsWithPagination;
    protected _getAuthorizationHeader(): Promise<string | undefined>;
}
