/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as StratifyX from "../../../../api/index";
import * as core from "../../../../core";
export declare const GetApiV1StudiesExecutionsExecutionIdOrdersRequestSortDirection: core.serialization.Schema<serializers.GetApiV1StudiesExecutionsExecutionIdOrdersRequestSortDirection.Raw, StratifyX.GetApiV1StudiesExecutionsExecutionIdOrdersRequestSortDirection>;
export declare namespace GetApiV1StudiesExecutionsExecutionIdOrdersRequestSortDirection {
    type Raw = "asc" | "desc";
}
