/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as StratifyX from "../../../../api/index";
import * as core from "../../../../core";
export declare const PostApiV1StudiesExecutionsExecutionIdOrdersFilteredRequestSortDirection: core.serialization.Schema<serializers.PostApiV1StudiesExecutionsExecutionIdOrdersFilteredRequestSortDirection.Raw, StratifyX.PostApiV1StudiesExecutionsExecutionIdOrdersFilteredRequestSortDirection>;
export declare namespace PostApiV1StudiesExecutionsExecutionIdOrdersFilteredRequestSortDirection {
    type Raw = "asc" | "desc";
}
