/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as StratifyX from "../../../../api/index";
import * as core from "../../../../core";
export declare const GetApiV1HealthResponse: core.serialization.ObjectSchema<serializers.GetApiV1HealthResponse.Raw, StratifyX.GetApiV1HealthResponse>;
export declare namespace GetApiV1HealthResponse {
    interface Raw {
        status: string;
    }
}
