/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as StratifyX from "../../../../api/index";
import * as core from "../../../../core";
export declare const GetApiV1MetadataMethodRequestMethod: core.serialization.Schema<serializers.GetApiV1MetadataMethodRequestMethod.Raw, StratifyX.GetApiV1MetadataMethodRequestMethod>;
export declare namespace GetApiV1MetadataMethodRequestMethod {
    type Raw = "transforms" | "commission" | "epoch_folio_category" | "order" | "position" | "round_trip" | "futures_continuation" | "slippage" | "timeframes" | "transforms_category" | "assets" | "indices" | "index_constituents";
}
