/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as StratifyX from "../../../index";
export declare namespace StudiesExecutions {
    interface Options {
        environment?: core.Supplier<environments.StratifyXEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        fetcher?: core.FetchFunction;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class StudiesExecutions {
    protected readonly _options: StudiesExecutions.Options;
    constructor(_options?: StudiesExecutions.Options);
    /**
     * @param {StudiesExecutions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     *
     * @example
     *     await client.studiesExecutions.listExecutions()
     */
    listExecutions(requestOptions?: StudiesExecutions.RequestOptions): core.HttpResponsePromise<string[]>;
    private __listExecutions;
    /**
     * @param {StratifyX.ExecuteRequest} request
     * @param {StudiesExecutions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     *
     * @example
     *     await client.studiesExecutions.startExecuteAStudy({
     *         id: "id",
     *         period: {
     *             start: "2023-01-15",
     *             end: "2023-01-15"
     *         }
     *     })
     */
    startExecuteAStudy(request: StratifyX.ExecuteRequest, requestOptions?: StudiesExecutions.RequestOptions): core.HttpResponsePromise<StratifyX.IdResponse>;
    private __startExecuteAStudy;
    /**
     * @param {string[]} request
     * @param {StudiesExecutions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     *
     * @example
     *     await client.studiesExecutions.bulkDeleteExecutions(["string"])
     */
    bulkDeleteExecutions(request: string[], requestOptions?: StudiesExecutions.RequestOptions): core.HttpResponsePromise<StratifyX.MessageResponse>;
    private __bulkDeleteExecutions;
    /**
     * @param {string} executionId
     * @param {StratifyX.GetApiV1StudiesExecutionsExecutionIdRequest} request
     * @param {StudiesExecutions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     * @throws {@link StratifyX.NotFoundError}
     *
     * @example
     *     await client.studiesExecutions.getExecutionById("executionId")
     */
    getExecutionById(executionId: string, request?: StratifyX.GetApiV1StudiesExecutionsExecutionIdRequest, requestOptions?: StudiesExecutions.RequestOptions): core.HttpResponsePromise<StratifyX.JobListItem>;
    private __getExecutionById;
    /**
     * @param {string} executionId
     * @param {StratifyX.DeleteApiV1StudiesExecutionsExecutionIdRequest} request
     * @param {StudiesExecutions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     *
     * @example
     *     await client.studiesExecutions.deleteExecutionById("executionId")
     */
    deleteExecutionById(executionId: string, request?: StratifyX.DeleteApiV1StudiesExecutionsExecutionIdRequest, requestOptions?: StudiesExecutions.RequestOptions): core.HttpResponsePromise<StratifyX.MessageResponse>;
    private __deleteExecutionById;
    /**
     * @param {string} executionId
     * @param {StratifyX.PostApiV1StudiesExecutionsExecutionIdCancelRequest} request
     * @param {StudiesExecutions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     *
     * @example
     *     await client.studiesExecutions.cancelExecution("executionId")
     */
    cancelExecution(executionId: string, request?: StratifyX.PostApiV1StudiesExecutionsExecutionIdCancelRequest, requestOptions?: StudiesExecutions.RequestOptions): core.HttpResponsePromise<StratifyX.MessageResponse>;
    private __cancelExecution;
    protected _getAuthorizationHeader(): Promise<string | undefined>;
}
