# This file was auto-generated by Fern from our API Definition.

import typing

GetApiV1DocsNameRequestName = typing.Union[
    typing.Literal["overview.md", "script_grammar.ebnf", "execution_guide.md", "timeframe_guide.md", "examples.txt"],
    typing.Any,
]
