/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as StratifyX from "../../../index";
export declare namespace StudiesPositions {
    interface Options {
        environment?: core.Supplier<environments.StratifyXEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        fetcher?: core.FetchFunction;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class StudiesPositions {
    protected readonly _options: StudiesPositions.Options;
    constructor(_options?: StudiesPositions.Options);
    /**
     * @param {string} executionId
     * @param {StratifyX.GetApiV1StudiesExecutionsExecutionIdPositionsFilterMetadataRequest} request
     * @param {StudiesPositions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     *
     * @example
     *     await client.studiesPositions.getPositionFilterMetadata("executionId")
     */
    getPositionFilterMetadata(executionId: string, request?: StratifyX.GetApiV1StudiesExecutionsExecutionIdPositionsFilterMetadataRequest, requestOptions?: StudiesPositions.RequestOptions): core.HttpResponsePromise<StratifyX.TableFilterMetadata>;
    private __getPositionFilterMetadata;
    /**
     * @param {string} executionId
     * @param {StratifyX.GetApiV1StudiesExecutionsExecutionIdPositionsRequest} request
     * @param {StudiesPositions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     *
     * @example
     *     await client.studiesPositions.getPositionsTabularJson("executionId")
     */
    getPositionsTabularJson(executionId: string, request?: StratifyX.GetApiV1StudiesExecutionsExecutionIdPositionsRequest, requestOptions?: StudiesPositions.RequestOptions): core.HttpResponsePromise<StratifyX.PositionRows>;
    private __getPositionsTabularJson;
    /**
     * @param {string} executionId
     * @param {StratifyX.PostApiV1StudiesExecutionsExecutionIdPositionsFilteredRequest} request
     * @param {StudiesPositions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link StratifyX.BadRequestError}
     *
     * @example
     *     await client.studiesPositions.getPositionsWithFilterExpression("executionId", {
     *         body: {
     *             conditions: [{
     *                     columnName: "column_name",
     *                     operatorType: "Equals",
     *                     values: ["values"]
     *                 }],
     *             logicalOperators: ["And"]
     *         }
     *     })
     */
    getPositionsWithFilterExpression(executionId: string, request: StratifyX.PostApiV1StudiesExecutionsExecutionIdPositionsFilteredRequest, requestOptions?: StudiesPositions.RequestOptions): core.HttpResponsePromise<StratifyX.PositionRows>;
    private __getPositionsWithFilterExpression;
    protected _getAuthorizationHeader(): Promise<string | undefined>;
}
